### ISSUE TITLE
Document how to install zsh completion script

### ISSUE THREAD

**Issue by jmwatte** [beetbox/beets#1731]
changed shell to zsh(prezto)

added the extra/_beet  for completion
but get 

    zsh completion : error _beet:local:155: options: can't change type of autoloaded parameter

thats

    local -a options regex_words_subcmds regex_words_help

Anyone any idea?
thx
jmw

**Comment by sampsyo** [comment]
I'm not familiar with the zsh completion script, so I'll need to let someone else comment.

**Comment by daveisadork** [comment]
I ran into this same thing. Evidently, this error happens if you do something like `source ~/Projects/beets/extras/_beet` in your `.zshrc`. What you need to do instead is put `_beet` in one of the directories that's in your `fpath`. On Debian based systems, `/usr/local/share/zsh/site-functions` is probably a good choice. Try doing `echo $fpath` to get a list of your options.

**Comment by sampsyo** [comment]
Good tip; thanks, @daveisadork! Any chance I could convince you to add a note to the docs in `docs/reference/cli.rst` under the "zsh" heading?

**Comment by daveisadork** [comment]
I'll try to remember to do that this weekend :)

**Comment by sampsyo** [comment]
Woohoo; thanks!
