### ISSUE TITLE
New URL has broken AppVeyor

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#1889]
It looks like the new URL of `beetbox/beets` has stopped AppVeyor tests being run (https://ci.appveyor.com/project/beetbox/beets returns a 404, and https://ci.appveyor.com/project/sampsyo/beets hasn't been updated since the rename). It also looks like any new PRs aren't being tested by AppVeyor.

**Comment by sampsyo** [comment]
Thanks! Travis reconfigured itself more or less automatically, so I forgot to check AppVeyor. I set up a new "project" there, since it doesn't seem possible to move the pointer to the new location.

Sadly, it got this ugly URL instead of the logical one: https://ci.appveyor.com/project/sampsyo/beets-p7x48/

**Comment by jackwilsdon** [comment]
That's odd, did you create it as the organisation or as your user?

**Comment by sampsyo** [comment]
Well, that's the thing—I can't figure out how to create the project "as an organization." The [appveyor docs](https://www.appveyor.com/docs/team-setup#github-teams) are incredibly confusing on this point—I think it's saying I would need to change *my* account name to `beetbox`? Because I don't think I can log in *as* the GitHub org separately from my personal account...

**Comment by jackwilsdon** [comment]
Yeah it's looking that way :disappointed:.

After reading this [help topic](http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations), it does seem you'd either need to create a whole new AppVeyor account with the name `beetbox` or change your AppVeyor username to `beetbox`.

**Comment by sampsyo** [comment]
So weird. I broke down and made a new account called `beetbox`, so now we at least have a useful URL! https://ci.appveyor.com/project/beetbox/beets
