### ISSUE TITLE
Star imports now issue a warning in flake8

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2052]
This has been in pyflakes, but is now surfaced by flake8. You can read about that here: https://gitlab.com/pycqa/flake8/merge_requests/56

Only the `logging` module is affected.

I added `F405` to the ignore list (https://github.com/beetbox/beets/commit/167544bcbee48e97213b327ab9a7ceb721845dbb) just to fix the build. I hope we can avoid keeping it.

I was under the impression that `# noqa` actually did something here, but I guess it doesn't?

**Comment by sampsyo** [comment]
OK, that seems fine! By my reading, the reason `noqa` seemed not to have an effect here is that the new error is about *uses*, not about the import itself. So we could mark all of the references with their own `noqa`, or just disable this error as you have done. Since this is a special case for the one-off `logging` shim, the latter seems fine to me.

**Comment by jackwilsdon** [comment]
You should be able to use `# noqa ignore=F405` to just ignore `F405`, but it needs to be on the same line as error.

e.g.

```python
from logging import *  # noqa ignore=F405
```
