### ISSUE TITLE
add a CONTRIBUTING.md file describing how to contribute to the project

### ISSUE THREAD

**Issue by jrobeson** [beetbox/beets#2103]
See https://help.github.com/articles/setting-guidelines-for-repository-contributors/ for details

**Comment by sampsyo** [comment]
I'm for it.

**Comment by jrobeson** [comment]
So, these tend to be markdown documents, but would we want the content in the documentation too? Also, how does it jive with the Hacking wiki page?

**Comment by sampsyo** [comment]
Good question. Here's one possible route (not necessarily the best one):

* Move the content from the Hacking wiki page to the main Sphinx docs.
* Make the CONTRIBUTING file point to the docs for most of the technical stuff.
* CONTRIBUTING also contains the CoC link and overview—i.e., the nontechnical aspects.

**Comment by jackwilsdon** [comment]
That sounds good to me; keep the main body of the documentation as Sphinx docs but add some information on the CoC to it.

What does GitHub think of using `.rst` for the `CONTRIBUTING` file? [Their documentation](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) is a bit vague:

> Contributing guidelines filenames are not case sensitive, and **can have an extension such as .md or .txt**.

It looks like [MongoDB uses `CONTRIBUTING.rst`](https://github.com/mongodb/mongo/blob/master/CONTRIBUTING.rst), so it should work.

We're probably best putting it in the root directory instead of `.github`, as it's more of a general guideline than something GitHub-specific such as the issue template.

**Comment by lengtche** [comment]
I was just talking to @sampsyo about this on IRC.

I did my first PR and had to go through the whole forking, cloning,  editable pip install, running tests locally, merging upstream to local before pushing to minimize conflicts, etc. While I'm not a new programmer by any means, it was my first time contributing to a project on GitHub. While it wasn't difficult, it did require a bit of tinkering before I got all pieces together.

I was thinking of submitting a PR once I get something fairly substantial in the Sphinx documentation.

**Comment by FlaviaBastos** [comment]
Hey @lengtche 
I am new to this project and also noticed the lack of info for contributions. I spent some time documenting the first few (very) basic steps and created a 'development setup' rst doc to go under the [For Developers](http://beets.readthedocs.io/en/v1.4.3/dev/index.html) page. 
I was wondering if you made any progress with this or/and if you would be willing to check what I have so far. Maybe we can combine efforts and move this forward.

Please note my notes are very basic and assume the reader is new to the project and git/GitHub.
I will submit a PR and flag you and @sampsyo 
Thanks
