### ISSUE TITLE
"Exporting" my library to a different path format

### ISSUE THREAD

**Issue by jackwilsdon** [beetbox/beets#2165]
Is it possible to export my library to a different path format?

For example, my current path format is `$albumartist/$album%aunique{}/$track $title` (the default one) and I'd like to copy my library to my MP3 player with the path format `$title - $artist`. I've tried doing it with the `convert` plugin but it seems to insist on converting lossless files (which I don't want to do).

On a semi-related note, does this path format do what I expect?

```
$title - $artist %if{%aunique{title artist, album},, - $album}
```

I don't really have any way to test it, but I'd expect it to name a file `TITLE - ARTIST` unless there is a duplicate and in which case it would call it `TITLE - ARTIST - ALBUM`. Is this right?

**Comment by sampsyo** [comment]
Hi, @jackwilsdon! Great to hear from you.

That is indeed the right role for `convert`. In fact, #1620 proposes to do pretty much exactly that: to disable transcoding, but do everything else that plugin does.

And that looks about right to me. You can always test path formats with `ls -f`, i.e.:

```
beet ls -f '$title - $artist %if{%aunique{title artist, album},, - $album}'
```

**Comment by wordofglass** [comment]
[geigerzaehler/beets-alternatives](https://github.com/geigerzaehler/beets-alternatives) seems to be the right tool to manage this. You can disable transcoding by not setting the `format:` option for your collection.

However, the plugin might be unsafe to use right now due to changes in recent beets. It suffers from the same logging problem described in #1467, although it probably does not cause breakage as it's not active during imports. I changed the logging in https://github.com/wordofglass/beets-alternatives/commits/adapt_to_new_beets. I'm not sure whether @geigerzaehler still is interested in maintaining the plugin, but I'll submit a PR at some point.

I don't know whether there've been other breaking changes in beets, at least a test run of `beet alternatives update` (with transcoding) worked fine for me today.

**Comment by intelfx** [comment]
Wow, beets-alternatives! I came here to to file an RFE for alternative locations and exporting — just to find out that this already exists.
