### ISSUE TITLE
Feature Request: API should return song/album paths

### ISSUE THREAD

**Issue by velvet-jones** [beetbox/beets#2177]
### Problem

We're writing a utility to synchronize music libraries and we could really use the ability to get the path to an album. Both for the web API and for the export plugin.
### Setup
- OS: Ubuntu 14.04.3
- Python version: 2.7.6
- beets version: 1.3.18
- Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is: N/A

**Comment by claman** [comment]
It's not perfect, but using the `info` command returns the path of the song in the first line

**Comment by sampsyo** [comment]
Hi! I think someone recently added a path field to the web API, in https://github.com/beetbox/beets/pull/2050#issue-159936072. Can you check that out?

**Comment by velvet-jones** [comment]
Thanks, we checked it and sure enough, there's a path - for individual tracks. Surely beets knows the path to each entire album in its database? I've been searching the code to try to figure out if the album path is possible to add to '/album'. Any ideas?

**Comment by sampsyo** [comment]
There's an `album.path` field in beets, but it's actually just the dirname of the first track on the album. Just stripping the file name off of the item path should work.

**Comment by irskep** [comment]
FYI I added paths to tracks in the web API in #2389. If that suffices, given @sampsyo's last comment, then this can probably be closed.

The history of this is a little confusing. #2050 added _relative_ paths originally. Then that was reverted due to #2182. Finally, I added it back behind a config flag in #2389. So people who need it can have it, and people who don't won't see a slowdown.

**Comment by sampsyo** [comment]
Thanks for following up, @irskep.
