### ISSUE TITLE
importer.py; asis and tagged comps

### ISSUE THREAD

**Issue by BevanBroun** [beetbox/beets#2181]
On an album where all tracks have albumartist as "Various Artist" but tracks have different artists, the importer doesnt recognise this as a compilation when "-A" (asis) is used.  

The behaviour makes sense when reading the code. I modified importer.py line 633 removing "i.albumartist or" to get the result I need.
Bevan@gonzilla>diff importer.py importer.comp_asis.py
633c633
## <                 [i.albumartist or i.artist for i in self.items]

> ```
>             [i.artist for i in self.items]
> ```

Bevan@gonzilla>beet -vv
user configuration: /cygdrive/d/dropbox/unix_home/.config/beets/config.yaml
data directory: /cygdrive/d/dropbox/unix_home/.config/beets
plugin paths:
Sending event: pluginload
lyrics: Disabling google source: no API key configured.
inline: adding item field multidisc
library database: /cygdrive/d/dropbox/unix_home/data/musiclibrary.blb
library directory: /d/music_beets
Sending event: library_opened
Usage:
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  --format-item=FORMAT_ITEM
                        print with custom format
  --format-album=FORMAT_ALBUM
                        print with custom format
  -l LIBRARY, --library=LIBRARY
                        library database file to use
  -d DIRECTORY, --directory=DIRECTORY
                        destination music directory
  -v, --verbose         log more details (use twice for even more)
  -c CONFIG, --config=CONFIG
                        path to configuration file
  -h, --help            show this help message and exit

Commands:
  clearart          remove images from file metadata
  config            show or edit the user configuration
  embedart          embed image files into file metadata
  extractart        extract an image from file metadata
  fetchart          download album art
  fields            show fields available for queries and format strings
  help (?)          give detailed help on a specific sub-command
  import (imp, im)  import new music
  list (ls)         query the library
  lyrics            fetch song lyrics
  modify (mod)      change metadata fields
  move (mv)         move or copy items
  remove (rm)       remove matching items from the library
  stats             show statistics about the library or a query
  super             do something super
  update (upd, up)  update the library
  version           output version information
  write             write tag information to files
Sending event: cli_exit

Led to this problem:
Compilation album with correct tags for albumartist and artists.
### Setup

multiple OS
multiple pythons 2.6.8 and a 2.7. 
beets version 1.36 to 1.40

config:
directory: /d/music_beets
library: ~/data/musiclibrary.blb
plugins: fetchart embedart lyrics inline bbplug discogs
asciify_paths: yes
paths:
    default: $albumartist_sort/$album/%if{$multidisc,Disc $disc/}$track $title
    singleton: $albumartist_sort/various/$title
    comp: Compilations/$album%aunique{}/$track $title
item_fields:
    multidisc: 1 if disctotal > 1 else 0
replace:
    '\ ': _

**Comment by sampsyo** [comment]
Interesting! Have you tried running the tests to see the impact? You can also open a pull request to have our CI service run them automatically.

**Comment by BevanBroun** [comment]
No - I havent tried running the tests. Ill try. I suspect the code change I did is not what is really wanted, just shows where the problem is (and helps me get my music in!). 

Im thinking of an:
     if (all tracks albumartsist == "Various Artists" )....

**Comment by m42i** [comment]
I've come across this myself and I'd remove the guessing of the album artist and compilation flag.

My music is tagged in a very specific way, so that I expect them to be reflected as-is in the beets database.

My criteria are:
- Soundtracks are always compilations
- If the soundtrack has multiple artists the album artist is empty. Not an empty string but actually not present. This way iTunes displays the album artist on compilations in a localised way. ("Verschiedene Künstler" on german systems, "Various Artists" on english systems, ...)
- Soundtracks by only one composer are still compilations but the albumartist is the composer. 
- Best of albums of a single artist are no compilations, but album artist is the artist

Is there a way to accomplish this without changing the code?

Interestingly the update command sets the comp flag correctly, although it sets the albumartist to the track artist on each track of my soundtrack compilations.
