### ISSUE TITLE
RFE: disable plugins from the command line

### ISSUE THREAD

**Issue by tweitzel** [beetbox/beets#2232]
It would be useful to issue a, say, --disable-plugins={ALL|pluginname} command when running beet. I have a half-working plugin in my path and config that I'm developing, but sometimes I just want to use the stable parts of beets like beet import or beet play without unexpected behavior. It would also be helpful for support inquiries to just tell people to put --disable-plugins=ALL in their command.

**Comment by sampsyo** [comment]
Cool! I see the use case, although it is pretty narrow. Have you considered creating a second config file that just contains:

```yaml
plugins:
```

and then using `beet -c pluginsoff.yaml ...`?

**Comment by arcresu** [comment]
Sounds like the second config file is a viable workaround for this pretty niche use case. Perhaps even the opposite setup would be useful: a second config file that only enables your WIP plugin so that you need to point to that file when developing?

If anyone really wants this feature enough, they should propose a specific implementation and see how invasive it is. That should probably happen after #607 when the plugin registry is added.
