### ISSUE TITLE
How to decompile sqlite? [The nightmare]

### ISSUE THREAD

**Issue by zeluspudding** [beetbox/beets#2241]
Hello! I read your [sqlite nightmare article](http://beets.io/blog/sqlite-nightmare.html) and would like to find out if I'm having a similar issue with my version of SQLite. 

I'm curious, how could I decompile sqlite to find whether I'm running `HAVE_USLEEP=0`?

**Comment by jrobeson** [comment]
there's a command/query in sqlite you can run to get the compile flags.  It shouldn't be too hard to find in the documentation, but I don't remember it off hand.

**Comment by zeluspudding** [comment]
Thanks for the quick reply! From python I run
```
import sqlite3
db = r"C:\Users\Artemis\Documents\Builds\secTrade\db\profiler.sqlite"
conn = sqlite3.connect(db)
with con:
    cur = con.cursor()
    cur.execute('PRAGMA compile_options')
    data = cur.fetchall()
```
but that only returns two compile time options

```
('SYSTEM_MALLOC',)
('THREADSAFE=1',)
```

What's more [this so post](http://stackoverflow.com/a/14199152/3491991) suggests it may not be possible to get all the compile time options if the option to display compile time options *at compile time* hadn't been enabled. Do you know whether `HAVE_USLEEP` missing from that list is a sign that some default was set?

**Comment by jrobeson** [comment]
i thought that SO post suggested that you might not be able to get the compile time options at all, not that some would be omitted.   I don't seem to see usleep either on my own machine either (Fedora 24).   Since @sampsyo suggested in the post that all his machines do, then I guess he should comment on this.

**Comment by jrobeson** [comment]
Oh, also, it's very clear that it's not explicitly enabled in the rpm spec file from which the package is built.

**Comment by sampsyo** [comment]
Yeah, that's exactly the technique that I used to check my machines. So my best guess is that your installation is unaffected.

**Comment by jrobeson** [comment]
@sampsyo : I'm confused. What OS/version was on the machine referenced in the blog post? what flags did they have set?  This makes me wonder if we should make sleeping for a full second either an  opt-in behavior or detect some other way.

**Comment by sampsyo** [comment]
It's been a while since I wrote that post, but I believe the problem came up on Debian-based systems.

This time, I managed to actually *read* my own writing to confirm what I said above, and it looks like I was wrong! Looks like I disassembled the SQLite dynamic library to check. The process would look like this:

1. Start Python and import sqlite3 to make sure the library is loaded
2. Use `lsof` to make sure you know which `sqlite3.so` or `sqlite3.dylib` is being used.
3. Use something like `objdump -d` to disassemble the library.
4. Look for the `sqliteDefaultBusyCallback` function.
5. Puzzle through the assembly to decide whether it looks like the usleep or non-usleep version of [the code](https://sourcecodebrowser.com/sqlite3/3.6.21/main_8c.html#ae3cee846ec02a003eb8299ad1a1cdbf1). It's not quite as easy as looking for the call, since it's an indirect branch, but one telltale sign is whether the multiply instruction is by 1000 or 1000000. For example, the telltale instruction on my SQLite installed by Homebrew is `imull   $1000, %edx, %esi`, indicating that it does not have the problem
