### ISSUE TITLE
random:  Return random tracks by time constraint

### ISSUE THREAD

**Issue by bearcatsandor** [beetbox/beets#2305]
It would be really cool to have a random by time function. Such that when you had 30 minutes before you raced out the door, you could give the random command a time and it would pick tracks that would fit within that time constraint.

Then the resulting tracks could be piped to other commands, and utilized for the "play" command as well.

One could do:

beet random -t 37 
to return 37 minutes of random tracks 

beet random -t 45 "Metallica" 
to return 40 minutes of random Metallica 

beet random -t 120 title:cats
 to return 2 hours of random tracks with the word "cats" in the title.

If one didn't have 2 hours worth of tracks with the word "cats" in them, it would just return as much as it can.

Random could be set up to return a defined number of tracks as well, but that's another Issue.

**Comment by diomekes** [comment]
I've made changes to the random plugin to implement this.  I won't open a pull request because it has other changes that I made for #2304, but here's a pastebin of it:

https://ptpb.pw/tJ4N

**Comment by bearcatsandor** [comment]
That looks awesome and better than i'd dreamed! Thank you!!!

**Comment by sampsyo** [comment]
Nice work, @diomekes! This looks awesome. I'd love to merge the new feature separately if you're amenable to splitting up the patches.

**Comment by diomekes** [comment]
Yes, I can do that.  I'll add the code to the current random plugin (which does not define several functions, just the main one, so I'll add the code under that function).

Can I run the tests that github runs on pull-requests on my end (either off-line or through github) so I can fix small issues before requesting a pull?

**Comment by sampsyo** [comment]
Yes, awesome! Thank you!

Here are some tips on running tests: https://github.com/beetbox/beets/wiki/Testing

And yes, please do add some docs (even just a draft is good).

**Comment by diomekes** [comment]
OK, I'm almost done with the plugin code.  Quick question: Should I make -e and -t mutually exclusive or should I add a if opts.time into the if opts.equal_chance?  Here are pastebins to see the two options:
https://ptpb.pw/_238
https://ptpb.pw/Z09i

**Comment by sampsyo** [comment]
Huh—interesting question. Can you explain intuitively how things work if -e and -t are used together?

**Comment by diomekes** [comment]
I'll try, if I understand -e correctly.

-e chooses a song by first making a list of artists and choosing a random artist from that list (instead of a list of songs, and choosing a random song).  That way, it doesn't matter how many songs from each artist you have, all artists are treated equal and once it chooses all the songs from one artist, that artist is deleted from the list.

With -n, it does that N times.

With -t, it does it until it reaches -t minutes, or more exact it stops if it can't find any song that would keep it under the minutes.

I like to use -e because it seems more random to me than without it, but the code looks kludgier to me (once again, I'm new at this, so there is a more elegant way I'm sure).

**Comment by sampsyo** [comment]
OK, thank you for explaining!

It sounds like the combination of the two would be good to keep. Feel free to open the PR as is; maybe we can sort out a simpler version of the code afterward.
