### ISSUE TITLE
discogs: Headings counting as tracks

### ISSUE THREAD

**Issue by thomsna** [beetbox/beets#2346]
### Problem

I'm trying to import this album:
https://www.discogs.com/Palle-Mikkelborg-Radiojazzgruppen-The-Mysterious-Corona/release/5292307

There is 11 tracks in this album, and each side of the LP has a heading, "The Mysterious Corona" and "M.B. Cyclus".

When importing the 11 tracks, the headings are seen as tracks, resulting in 2 missing tracks.

### Setup
```
$ uname -a
Linux x 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ beet version
beets version 1.4.1
Python version 2.7.12
plugins: badfiles, chroma, copyartifacts, discogs, embedart, fetchart, info, missing, scrub, web
```

**Comment by sampsyo** [comment]
Hmm, that's no good—I'm guessing this has to do with #2222, which addressed some other issues with those headings. Maybe it would be worth taking a look, @diego-plan9?

**Comment by diego-plan9** [comment]
My pleasure - thanks for pinging me, and thanks @thomsna  for the report!

While it seems that the handling of "heading tracks" is indeed in need of a revision, in this particular case I'm wondering if it is due to the duplicated positions of some tracks (B1 and B4), which according to [the discogs guidelines](https://www.discogs.com/help/doc/submission-guidelines-release-trk) seems to be not allowed as far as I can see (emphasis mine):



> 12.2.1. The position field (Pos) is where the track position number is entered. **The positions used need to be unique** - you can't have two tracks both with the same position ('A1', for example). If there is position numbering in the main credit section, it must be identical to the position numbering in the tracklisting.

In practice, the duplicated positions seems to be causing that the list of tracks generated by the plugin (ie. used for the matching) contains indeed 13 items, but it does not include the heading tracks but the duplicated tracks. Could you please confirm that, on the interactive prompt, ie:

```
$ beet import -t /path/to/album -S https://www.discogs.com/Palle-Mikkelborg-Radiojazzgruppen-The-Mysterious-Corona/release/5292307
```
the list of tracks to be matched (and missing) contains all the regular track titles (and not the index track titles)? While trying to reproduce the issue, this is the list of track titles that seems to be generated after parsing the release:
```
[u'Corona', u'Overwhelming Emotion', u'Cosmos', u'Birds Fly', u'Religous Feeling', u'Magic', u'Awe', u'Ming', u'Short Cart', u'La Mijas', u'Mongolia', u'Beauty M.', u'Free Bee']
```

**Comment by thomsna** [comment]
Hi @diego-plan9,

You're totally right – I made the wrong assumption that the headings were the culprit.
The folder containing the album had only 11 tracks, because tracks B1 and B4 contain two pieces each.
Track B1 is "Ming & Short Cart"
Track B4 is "Beauty M. & Free Bee"
The creator of the Discogs entry separated them each in two tracks with the same index, which as you've shown is wrong according to Discogs.
I assume the correct way is to name track B1 and B4 as above.

Sorry for the rambling, and there is no bug!

**Comment by sampsyo** [comment]
Thanks for checking back in, @thomsna!
