### ISSUE TITLE
Disallow `import <library>`

### ISSUE THREAD

**Issue by nils-werner** [beetbox/beets#2377]
### Problem

After briefly reading the tutorial, I set up `beet` with a library and was ready to run it. However, what I did know is that where the music was currently wasn't allowed to be my library location. So **inside** what was supposed to end up being my library, I ran

```sh
$ beet import .
```

This led to `beet` finding and copying files. But since the source and target directories were in the same place, it created a big mess in there.

`beet` shouldn't allow `import <library>` as it is very unlikely the user really wants the mess that might ensue.

### Setup

* OS: OSX Maverick
* Python version: 2.7
* beets version: 1.4.2
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is:

```yaml
directory: ~/Medien/Musik
library: ~/Medien/Musik.blb
```

**Comment by sampsyo** [comment]
I agree that it's usually not what you want—unless you've turned off `copy` mode or replaced it with `move`, in which case this might actually be what you want. That's why [the first couple of sections of our guide](http://docs.beets.io/en/v1.4.2/guides/main.html#configuring) describe how to manage the directories and strongly recommend you keep the source separate from the destination.

I don't know if we'll ever be able to avoid all—or even a significant fraction—of ways beets can be misused without also making things annoying for merely uncommon, but not clearly wrong, use cases. Is there some way we can make it clearer in the documentation that you probably shouldn't do this?

**Comment by irskep** [comment]
The `beet import` docs seems to explicitly suggest that this is a well supported operation, moving files around instead of copying them. http://docs.beets.io/en/v1.4.2/reference/cli.html#reimporting

**Comment by bmhm** [comment]
I'd suggest:
If copy is set to on, warn the user and show an additional promt:

> The folder you are trying to import is a (sub)folder of your library. Also, copy mode is set to on which will potentially result in a lot of duplicated files. Is this really what you want to do? If not, consider switching "copy" to off and "move" to on to re-tag and rename your library.
> [P]roceed anyway (might result in copied files), a[B]ort, use [C]opy off just for this operation (just tagging, no renaming/moving), use [M]ove just for this operation (tagging, renaming and moving).
