### ISSUE TITLE
Does beets use musicbrainz by default instead of discogs?

### ISSUE THREAD

**Issue by thomsna** [beetbox/beets#2391]
When importing an album, does beets prioritise a database? (I generally prefer the discogs database to musicbrainz).

### Setup
```
$ beet version
beets version 1.4.3
Python version 2.7.12
plugins: badfiles, chroma, copyartifacts, discogs, embedart, fetchart, info, missing, scrub, web
```

**Comment by lengtche** [comment]
It does indeed prioritize MusicBrainz over Discogs.

Like you, I prefer Discogs mainly because it offers far more metadata that MusicBrainz is unable to handle.

You can import from Discogs into MusicBrainz within seconds by using one the user scripts found in this [repository](https://github.com/murdos/musicbrainz-userscripts).

**Comment by sampsyo** [comment]
Yes; plugin-provided sources have a small penalty applied. You can set the `source_weight` config option under the `discogs` section to 0.0 to disable this penalty.
