### ISSUE TITLE
Question re. Guide (main.rst)/ Seeing your Music

### ISSUE THREAD

**Issue by mskadu** [beetbox/beets#2463]
According to the Getting Started Guide, section "Seeing your music"

> As you can see, search terms by default search _all attributes_ of songs

I don't think that's entirely accurate. Here's an example. 

I start with ``beet ls sa``
```
d:\downloads>beet ls sa
[MP3][hin] Mere Sanam (1965) - Asha Bhosle - Jaiye Aap Kahaan Jayenge
[MP3][hin] Mere Sanam (1965) - Asha Bhosle - Yeh Hai Reshmi Zulfon Ka Andhera
[MP3][hin] Mere Sanam (1965) - Asha Bhosle & Mohammed Rafi - Humne Toh Dil Ko Aapke Kadmon Pe
[MP3][hin] Saathiya (2002) - A. R. Rahman - Mera Yaar Mila De
[MP3][hin] Saathiya (2002) - Adnan Sami - Aye Udi Udi Udi
[MP3][mul] Rock On!! (2010) - Shankar-Ehsaan-Loy - Ye Tumhari Meri Baatein
[MP3][mul] Rock On!! (2010) - Shankar-Ehsaan-Loy - Phir Dekhiye
[MP3][] Virasat (1997) - Virasat - Payalay Chunmun Chunmun
```
And then I do a ``beet ls 1965`` - this returns zero items. But doing a ``beet ls year:1965`` I get
```
[MP3][hin] Mere Sanam (1965) - Asha Bhosle - Jaiye Aap Kahaan Jayenge
[MP3][hin] Mere Sanam (1965) - Asha Bhosle - Yeh Hai Reshmi Zulfon Ka Andhera
[MP3][hin] Mere Sanam (1965) - Asha Bhosle & Mohammed Rafi - Humne Toh Dil Ko Aapke Kadmon Pe
```

In short, clearly the year field is not being searched when I do ``beet ls 1965``.

Questions
1. which fields are searched when I don't explicitly specify a field name.
2. How do I search for a particular field being blank (e.g. language field in the last item in the first list of files)

Thanks.

**Comment by sampsyo** [comment]
Good point; the default isn't to search all fields—it's to search a pre-defined list of commonly used fields. The list is here in the source: https://github.com/beetbox/beets/blob/master/beets/library.py#L471-L472

And here in the docs: http://docs.beets.io/en/v1.4.3/reference/query.html#keyword

So that sentence in the guide could use some massaging.

---

To search for a blank value, use a regular expression: ``beet ls language::^$``

**Comment by sampsyo** [comment]
OK, clarified that language and linked to the authoritative source.
