### ISSUE TITLE
Advanced Awesomeness (advanced.rst)

### ISSUE THREAD

**Issue by mskadu** [beetbox/beets#2465]
The page intros with

> So you have beets up and running and you’ve started  :doc:`importing your music </guides/tagger>`. There’s a lot more that beets can do now that it has cataloged your collection.

Does it make sense for this link to point to /guides/main.html#importing-your-library instead? IMHO, it should because it is in line with what the intro implies.

Also, I was unable to find a way to target a Title within a separate page in the Rst syntax? Would you happen to know how?

**Comment by sampsyo** [comment]
Well, since this page is supposed to come *after* you've really gotten familiar with beets, so I feel pretty comfortable linking to the more advanced importer guide. Think of it as step 3 after the first two steps (`main` and `tagger`).

You can link to a particular section by putting a label before the title, like this:

```rst
.. _somelabel:

My Section
==========
```

Then, you link to it with ``:ref:`somelabel` ``. There are a few examples of this in our docs if you're curious.

**Comment by mskadu** [comment]
Um, Ok.

As for your answer, perhaps I need to expand. I was after being able to
link to "Importing your library" sitting inside main.rst from within
advanced.rst

The HTML equiv (in advanced.html) would have been

... <a href="main.html#importing-your-library">importing your music</a> ....









--
Mayuresh

**Comment by sampsyo** [comment]
OK, thanks for understanding! Maybe we should make it clearer from the text that that's what we're linking to?

For what it's worth, the kind of link you're looking for, I believe, is written ``:ref:`title <label>` ``.
