### ISSUE TITLE
Is it Possible to Query Beets by File Type?

### ISSUE THREAD

**Issue by Stunner** [beetbox/beets#2610]
As the title says, I am wondering if I can search beets by file type (so that I can pinpoint which artists need to be reimported in order to convert them to a desired format).

**Comment by sampsyo** [comment]
Sure is!

```
beet ls format:MP3
```

**Comment by Vesnyx** [comment]
An addendum to this question. Is there a way to list the albums that contain a certain file format? I'd like to use a command like `beet ls -a format:FLAC`, but unfortunately this doesn't work. Is there a way to have it display like this or would I need to write a plugin to do so?

**Comment by sampsyo** [comment]
Good point. We don't have an album-level $format field because albums can have multiple formats, but it's possible to define one using the `inline` plugin and a little bit of Python. I know this has even been discussed before—I was unable to find it quickly, but the answer may be in the issue tracker or the mailing list archives. In any case, the precise incantation will look pretty similar to the "album-level bitrate" example we have [in the docs for the inline plugin](http://docs.beets.io/en/v1.4.5/plugins/inline.html#album-fields).

**Comment by Vesnyx** [comment]
If anyone else is looking for something like this, here's what I used in the 'inline' plugin config, and it seems to work properly for me.
```
album_fields:
    format: |
        formatList = []
        for item in items:
            formatList.append(item.format)
        return formatList
```
