### ISSUE TITLE
Supporting MusicBrainz _releasecomment for Album Disambiguation

### ISSUE THREAD

**Issue by kilemensi** [beetbox/beets#2639]
The current disambiguation fields such as `albumtype`, `year`, etc. work well for the case when a band releases distinct albums but with the same name. But nowadays it's more common for the label to re-release the same album but with minor differences such as expanded edition, remastered, X years anniversary edition, etc.

MusicBrainz uses `_releasecomment` field to store this information but there is no way to access this information from the current beets version i.e. `1.4.5`.

**Comment by sampsyo** [comment]
Hello—I’m pretty sure the field you’re referring to is available as `$albumdisambig`. Have you tried that field?

**Comment by kilemensi** [comment]
Hi.

Just had a quick test and can confirm this is exactly what I was looking for. Spent at least an hour going through the docs and for some reason I totally missed it.

Thanks you.

PS: May be we should add a line or two explaining that this filed maps to _releasecomment if tags come from MB.

**Comment by sampsyo** [comment]
Woohoo; that’s great! Yes, it would be a good idea to mention it in the docs. The hardest part will be figuring out the right place to mention it so that the people who need to find the tag will see it. :smiley: Any chance you might be able to make a small edit to insert a mention at an appropriate place? (Thank you!)
