### ISSUE TITLE
Should aunique()'s bracket argument default to None?

### ISSUE THREAD

**Issue by RollingStar** [beetbox/beets#2672]
https://github.com/beetbox/beets/blob/aa195774646715bc317c9ca1e6f5340ade3f05cb/beets/library.py#L1482

```
    def tmpl_aunique(self, keys=None, disam=None, bracket=None):
        # snip
        if bracket is None:
            bracket = '[]'
```

Was it written this way to avoid a Python quirk? I've found some discussion of this on the Internet, but I'm not sure if it applies here.

https://stackoverflow.com/questions/13195989/default-values-for-function-parameters-in-python

http://docs.python-guide.org/en/latest/writing/gotchas/

**Comment by sampsyo** [comment]
Hmm; good question. It’s not the mutability thing, fortunately, because strings are immutable in Python.

But it could be because of how the beets template expansion logic works: it might fill in None itself for arguments that aren’t provided (although this seems unlikely). Maybe it’s worth experimenting with?

**Comment by RollingStar** [comment]
don't know why it was written this way, could be clearer if it's not needed.

**Comment by sampsyo** [comment]
If you're interested, would you mind giving the simpler version a try and seeing if everything still works?

**Comment by RollingStar** [comment]
On my todo list
