### ISSUE TITLE
%aunique fails if a disambiguation is a non-fixed field

### ISSUE THREAD

**Issue by devster31** [beetbox/beets#2678]
I recently encountered this behaviour while trying out paths with `%aunique{}` and the below config.
```yaml
paths:
    default: $albumartist/$albumartist - $album%ifdef{albumdisambig, - $albumdisambig}%aunique{albumartist album year, catalognum label} [$format]/%if{$multidisc,$disc-}$track. $title
```
This will produce the below output (part of).
```text
Franz Ferdinand - Franz Ferdinand [678] [MP3]
Franz Ferdinand - Franz Ferdinand [679] [FLAC]
```
This means that different format, which already produce a different path, still get deduplicated by `%aunique`, which is intended behaviour.
I would, however, want to avoid this and @sampsyo  referred to #2610, from which I slightly adapted this snippet:
```yaml
album_fields:
    albumformat: |
        format_list = []
        [format_list.append(item.format) for item in items if item.format not in format_list]
        return format_list
```
The snippet works for the `beet list` command, however it does not work as a _disambiguator_ for `%aunique`:
```yaml
paths:
    default: $albumartist/$albumartist - $album%ifdef{albumdisambig, - $albumdisambig}%aunique{albumartist album year albumformat, catalognum label} [$format]/%if{$multidisc,$disc-}$track. $title
```
And produces `_no such column∶ format_` in the file name.
I believe this is caused by this piece:
```py
        for key in keys:
            value = album.get(key, '')
            subqueries.append(dbcore.MatchQuery(key, value))
```
found in [`beets/library.py`](https://github.com/beetbox/beets/blob/34246a00e7be8da59ed4e0d659f7b980a5da7910/beets/library.py#L1525-1528).
My understanding is that the `key` gets queried to the database but not with the fields generated by the `inline` plugin. Would it be feasible to allow `inline` fields to be queried?

### Setup

* OS: Raspbian + Docker
* Python version: 3.6.1
* beets version: 1.4.5
* Turning off plugins made problem go away (yes/no): no

**Comment by RollingStar** [comment]
I've found responses like this `_no such column∶ format_` in my own use of aunique(). Have you tried a path format like this?

`%aunique{albumartist album year $albumformat, catalognum label}`

Notice the `$`. You need $ in the first set of disambiguators for any field defined with inline. You need to *not* use $ in the second set of disambiguators. Example:

`%aunique{albumartist album year $albumformat, cust_field catalognum label}`

**Comment by devster31** [comment]
This is my output after your suggestion:
```sh
$ beet ls -f '$albumartist - $album %aunique{albumartist album year $albumformat, catalognum label} [$format]' album::^Franz Ferdinand
Franz Ferdinand - Franz Ferdinand <no such column: 'MP3'> [MP3]
Franz Ferdinand - Franz Ferdinand <no such column: 'MP3'> [MP3]
Franz Ferdinand - Franz Ferdinand <no such column: 'FLAC'> [FLAC]
```
It could be something related to my setup though.

**Comment by sampsyo** [comment]
Thanks for the detailed report. This is in fact a bug—I don't think even a flexible attribute would work as a disambiguator as it stands. The problem is indeed with the MatchQuery construction that you pointed to. Namely, the problem is that the FieldQuery base class constructor defaults to `fast=True`, which only works for fixed fields: https://github.com/beetbox/beets/blob/34246a00e7be8da59ed4e0d659f7b980a5da7910/beets/dbcore/query.py#L102

To read more about fast and slow queries, check out [this blog post](http://beets.io/blog/flexattr.html). We need to pass `True` for the `fast` parameter when the field name is non-fixed.

The right fix is probably a helper function that will automatically choose the fast parameter based on the kind of field being queried.
