### ISSUE TITLE
Don't try to match non-audio media fetched from MusicBrainz

### ISSUE THREAD

**Issue by zuzzurro** [beetbox/beets#2688]
Matching a folder containing all audio files of a MB release made of CD+DVD for instance fails since beets does take into account also the video files.
For instance (1 CD+ 1DVD):
https://musicbrainz.org/release/2775743e-2d9c-4b7f-9baa-1d24dc44c769
https://musicbrainz.org/release/f457c3e1-0d98-4904-9d9e-a085bc5b232b
I imagine the same happens for enhanced CDs with some additional video track.
In general I think the right thing to do is that all media files that are marked as video in MB should not be considered for matching. After all beets currently only deals with audio files.

**Comment by pprkut** [comment]
Sounds like #1210 and might be related to #1638

**Comment by sampsyo** [comment]
Indeed! Let’s track this in #1210.

**Comment by nguillaumin** [comment]
I think that's actually a slightly different issue that may need separate consideration and re-opening.

#1210 is about having a single (or multiple) non-music tracks *inside a given medium*, mixed with audio tracks. See track 21 on [this](https://musicbrainz.org/release/49da37ee-065a-4d7f-a204-9dda8047aad4) - [xml](http://musicbrainz.org/ws/2/release/49da37ee-065a-4d7f-a204-9dda8047aad4?inc=artists+artist-credits+recordings+aliases)

This issue is about skipping a complete *medium*, for release that have CD+DVD for example. See [this](https://musicbrainz.org/release/1082195b-9b14-466f-a443-7cf830f64316) - [xml](http://musicbrainz.org/ws/2/release/1082195b-9b14-466f-a443-7cf830f64316?inc=artists+artist-credits+recordings+aliases)

In the later case, the medium to skip is identified by its `format` of type `DVD`:

```xml
<medium-list count="2">
  <medium>
    <position>1</position>
    <format id="9712d52a-4509-3d4b-a1a2-67c88c643e31">CD</format>
    <track-list count="10" offset="0">...</track-list>
  </medium>
  <medium>
    <position>2</position>
    <format id="2875c583-4580-3a90-b723-ba1b39921e23">DVD</format>
    <track-list offset="0" count="7">...</track-list>
  </medium>
</medium-list>
```
A list of formats is available [here](https://musicbrainz.org/doc/Release/Format)

Currently when trying to import this release, I get:

```
Tagging:
    Playing for Change - Songs Around the World
URL:
    https://musicbrainz.org/release/1082195b-9b14-466f-a443-7cf830f64316
(Similarity: 84.9%) (missing tracks) (2xCD, 2009, US, Hear Music)
CD 1
Missing tracks (7/17 - 41.2%):
 ! Stand by Me (#11)
 ! One Love (#12)
 ! War / No More Trouble (#13)
 ! Don't Worry (#14)
 ! Chanda Mama (#15)
 ! The Playing for Change Foundation (#16)
 ! Peace Through Music (#17)
[A]pply, More candidates, Skip, Use as-is, as Tracks, Group albums,
Enter search, enter Id, aBort?
```

**Comment by sampsyo** [comment]
Ah, I see! So they’re certainly related, but not exactly the same problem. Perhaps https://github.com/beetbox/beets/issues/2404 is a closer precedent?

**Comment by nguillaumin** [comment]
I think that's different too. #2404 is about alternative *audio* media, like a CD and a DVD-Audio, or a CD and a Digital Media. I think this issue is simpler, it's just about ignoring media that don't contain audio (such as DVD, or CD-Rom (data) disks).

**Comment by sampsyo** [comment]
Got it; thanks for helping to clarify. I'll reopen this and change the title.

**Comment by pprkut** [comment]
What would be a good way to make this optional? Boolean flag in the config? Or perhaps making the list of formats configurable?
Maybe there's a way to detect whether the tracks are present and only ignore missing media?
I like tracking audio-only versions of the video tracks with beets and would like to continue doing that
