### ISSUE TITLE
When importer is in incremental mode, offer an option to avoid recording the album

### ISSUE THREAD

**Issue by bviefhues** [beetbox/beets#2773]
It would be useful to have a "[L]ater" plugin that allows to non-permanently skip an import in incremental mode, in order to be processed again in subsequent import runs. That would basically be the "[S]kip" functionality, minus storing the path.

Typical use case would be, in a large volume import, to skip the difficult cases for the time being and to re-visit these later.

**Comment by sampsyo** [comment]
Interesting idea! For what it's worth, this is only relevant in `incremental` mode. By default, we don't record (or automatically skip) any paths. I've updated the title to describe the idea in more detail.

**Comment by sekjun9878** [comment]
@sampsyo Is this something that can be done with a plugin? Adding to the incremental list is done in the final stage of the pipeline, after all the plugin stages have passed.

**Comment by sampsyo** [comment]
Agreed; I don’t believe a plugin could do this currently.

Thanks for laying out these options! This is a good set of alternatives, and I always find it useful to map out the space of possible implementations ahead of time. :+1:

Here are some comments on each option:

1. This is the least obtrusive option, and it avoids bothering people who don’t need this feature with an extra prompt option. The only question is whether this is flexible enough—whether a “skip and record” action is ever useful in addition.
2. This is a more complex implementation, but it gets the behavior exactly as proposed.
3. This would be nice for future extensibility, but it runs the risk of unexpected consequences when aborting the pipeline early. For example, the “restartable” import feature wouldn’t get a chance to record progress.

Overall, I lean toward 1 if it doesn’t seem to limited, and probably 2 otherwise. Any opinions?
