### ISSUE TITLE
Sanitize tags

### ISSUE THREAD

**Issue by bviefhues** [beetbox/beets#2774]
I am playing music on a device that is not fully capable of displaying the character set emitted by Musicbrainz (for reference, the device is an Audi MMI). Most characters work, but some are shown wrongly. In order to fix that, I would appreciate having a flexible character translation functionality for sanitizing tags.

Note that this should be more flexible than just convert to 7-bit ASCII, German umlauts do work, for example. However, I do need to research a bit more which chars are good and which are problematic.

**Comment by sampsyo** [comment]
Hello! See https://github.com/beetbox/beets/issues/488 for a proposal about applying more flexible transformations to tags' values. With this, you can imagine replacing whatever characters you find that your device doesn't support.

I'll close this issue for now because I think it's more relevant to keep the discussion on #488.
