### ISSUE TITLE
possible changes to the types plugin

### ISSUE THREAD

**Issue by dkanada** [beetbox/beets#2840]
Could the types plugin include modification of regular field types such as disc and track? I noticed [here](https://github.com/beetbox/beets/blob/master/beets/library.py#L443) that a lot of the integer fields are actually padded integers. I would prefer to display my fields exactly as they are stored in the media files.

I looked through the code a bit and didn't see anything simple that would get this working. Does the types plugin hook in somewhere and specify the data type for every field or does it only currently have support for custom fields?

**Comment by sampsyo** [comment]
Here's what I would suggest for this: use the `inline` plugin too to define an alias and give a type to that field. For example, you could use:

```yaml
item_fields:
    my_disc: disc
types:
    my_disc: int
```

Does that do what you want?

**Comment by dkanada** [comment]
That would technically solve my issue but I would rather have a better solution. Would you consider a configuration option to pad integers so it could be disabled?

**Comment by sampsyo** [comment]
Hmm, I'm not sure… it could make sense if we can make the case that there's something deeper here, but adding a configuration option to something so global has a surprisingly high cost in maintainability and testability. So it would be awesome if there were some broader, underlying change we could make instead of a one-off config for this specific use case.

**Comment by dkanada** [comment]
closing as a duplicate of #3352
