### ISSUE TITLE
`grouping` field is ignored when set on albums, and doesn't sync between albums and tracks.

### ISSUE THREAD

**Issue by ToxicFrog** [beetbox/beets#2841]
### Problem

`beet import --set` can be used to set various fields on import, overriding the metadata in the files or inferred from MBZ. However, this override isn't applied as the files are imported; instead, it appears to work something like this:

For each album/track being imported:
- autotag
- move files into library

Once everything has been moved into the library:
- apply overrides
- move again if necessary

The problem here is that if `beet import` gets interrupted -- say, it crashes, or you have to `^\` it because it tried to ingest a directory containing 25,000 files and hung when you tried `^C` -- the `--set`s never get applied, so you're left with (potentially many) files that have been imported into the library but not tagged correctly, and now need to find and fix them.

### Proposed solution

`beet import` should apply overrides to each file or album immediately after autotagging, before the files are moved into position in the library.

### Setup

* OS: Linux (NixOS 17.09)
* Python version: 2.7.14
* beets version: 1.4.6
* Turning off plugins made problem go away (yes/no): no

**Comment by sampsyo** [comment]
Hello! It's actually not quite right that there's a "first move" followed by a tag update and a second move. It actually happens in the same stage as applying the metadata match:
https://github.com/beetbox/beets/blob/2941833f2227431ea1934da1e1bfb65d57bcf179/beets/importer.py#L1499

Is there possibly some other explanation for the behavior you're seeing?

**Comment by ToxicFrog** [comment]
Yeah, I've been investigating it more and it looks like the *real* issue may actually be that `beet import --set grouping=...` doesn't work at all, at least for albums. And it's `grouping` that I've been testing with.

There's some weirdnesses with grouping in general, e.g. `beet modify -a grouping=...` appears to succeed but doesn't affect how files are stored and doesn't change the per-track `grouping` field, and `beet import` doesn't reliably preserve grouping information (`contentgroup`/`TIT1`) already present in the files -- I wonder if this is another manifestation of the same underlying problem.

**Comment by sampsyo** [comment]
Aha, yes, I think the problem is the more general set of (admittedly confusing) issues about album versus track fields. I would expect `beet import --set grouping=...` to work, but it might currently *only* set the field on albums—not on the individual tracks. That would be weird and probably wrong.

See some similar discussion in https://github.com/beetbox/beets/issues/2797#issuecomment-360926531.

**Comment by ToxicFrog** [comment]
I think that gave me the insight needed to pin down what's actually happening here.

- `grouping` is both an album and an item field.
- **only the item field is respected** when organizing files. The album field shows up in `beet ls -a` with an appropriate format, but is *completely ignored* otherwise.
- `beet modify -a grouping=...` sets the album field but *not* the item field
- `beet import --set grouping=...` without `-s`, similarly, sets the album field but not the item field, and thus files end up being organized as if they had no `grouping`
- `beet import -s --set grouping=...` *does* set the item field appropriately

So the *real* bug here, I think, is that `grouping` can be set on either albums or tracks, but the album grouping is entirely ignored, and setting it doesn't automatically set it for the tracks in that album either.

**Comment by sampsyo** [comment]
Thanks for investigating! To clarify, some of the things listed here are true about `grouping` (and other flexible fields—more below) but not about album-level fields in general. Specifically:

- Typically, album-level fields such as `albumartist` override their item-level equivalents. We have actually special-cased path format expansion so that album-level data takes precedent, which leads to more consistent directory structures.
- Running `beet modify` or `beet import -a` sets *both* the album-level and item-level values for fields like `albumartist`.

The problem is that `grouping` is *not* an album-level built-in ("fixed") field, unlike `albumartist`. That's because that field is typically used as the label for individual discs within a box set (and similar sub-album groupings). So when you did `beet modify grouping=...` and the `import -s` equivalent, that created a *flexible* attribute on the albums that does not have the same properties—these do not automatically get item-level equivalents.

I'm not sure that's a great idea—it's possible that one would always want to propagate album-level flexible attributes to items—which is what the above-linked comment ponders.
