### ISSUE TITLE
Fetchart: Minimum Height

### ISSUE THREAD

**Issue by adam-blakey** [beetbox/beets#2874]
### Feature

It would be great to be able to specify a minimum width for artwork in the plugin 'fetchart'. This would work in a similar way to `minwidth`, and would be used in the Beets config file. Here's an example in the Beets config file:

```
...
plugins: fetchart

fetchart:
    minheight: 500
...
```

This would force the artwork to be added to be more than 500 pixels in height.

**Comment by sampsyo** [comment]
Thanks for filing! Could you perhaps expand a little bit about why this would be useful? Most artwork is square, which is why we have this setting and the ratio configuration. Are you running into non-square images where this is a problem? Could you perhaps give a few example of cases that can't be ruled out by a combination of `minwidth` and `enforce_ratio`?

**Comment by JustAdamHere** [comment]
I've had experiences where, for example, the artwork found might have 500-by-501 pixels, which would then be excluded from being added (although I would deem that good enough to be added to my albums). So not really non-square images as such, but rather near-square images (which I deem okay) are not going to be added.

**Comment by sampsyo** [comment]
Got it; that's very helpful!

I also note that the `enforce_ratio` option to the fetchart plugin allows some "fuzziness" its operation. For example, the docs say you can use `enforce_ratio: 10px` to allow images that are 10 pixels "out of square." Have you given that a try?

**Comment by JustAdamHere** [comment]
I must've missed that — that looks like it'll do the job! I can't think of any purposely non-square artwork so that's great. Thanks!
