### ISSUE TITLE
Replaygain album gain per disc support

### ISSUE THREAD

**Issue by yoasif** [beetbox/beets#293]
It'd be nice to be able to Replaygain albums with a per disc album gain grouping. 

So if I had a two CD album (using disc tags), each disc would have it's album gain calculated by itself, irrespective of the other discs in the same album.

**Comment by samuelnilsson** [comment]
Hi!

I'm opening this up almost 6 years later. I'm also interested in this feature and could try to implement it if it is not too time consuming. Do @sampsyo, who has more insight of the code, still believe this should be relatively straightforward? Personally I don't believe that it seems too complicated to achieve when looking at the plugin code.

However, one issue is that the rg_album_gain and r128_album_gain are album level fields. Will that structure need to be changed since, when implementing this, the items on an album could have different album gain values?

**Comment by sampsyo** [comment]
Sure! I agree that it shouldn’t be too complex.

It is unfortunate, but you’re also right that we may need to “demote” those fields to item-level fields. It is also technically possible, although a little weird, for items to “disagree” even on album-level fields—nothing actually prevents that from happening. So maybe it’s worth a try without changing the status of those fields, and we can revisit the decision if it causes problems.

**Comment by arcresu** [comment]
Closed in #3137
