### ISSUE TITLE
Is it possible to overwrite files?

### ISSUE THREAD

**Issue by xpelican** [beetbox/beets#2968]
Hello, and first of all thank you for creating beets. It is very handy and exactly what I was looking for to take care of my music archive. Brilliant work. I apologize in advance if the following is a stupid question, as I'm guessing this already exists within beets somehow, but I experimented for some time now and couldn't find anything related to this in any of the documentation I could find either.

I'm currently trying to use beets in an automated bash script focused on mountable external archives, and have it _overwrite_ music files on mounted drives after sorting them with the autotagger,  So, instead of copying/moving files to a different location (such as the host machines disk), I'd like to import them to library only and perform the normal autotagging / renaming operations for each file, but then change the original files with the new, properly named and tagged versions.

So far, the only way I could make this happen was around beets through the script I'm building (point beets to the externally mounted filesystem path, save properly formatted files from beets to host machine disk, delete the originals on external device, then move the new files in host machine back to the external device), and I'm wondering if there's somehow already a way to directly overwrite files within beets that I just couldn't figure out.

Again, apologies in advance if this is a noob question, and thanks for all your good work!

**Comment by sampsyo** [comment]
Hi! I'm glad you're interested. But I'm having a little trouble understanding exactly what you want. Specifically, I guess I'm not sure how it's different from just enabling the `move` option for the importer and having the source be the same as the destination (i.e., provide the same path to the `import` command as you have configured as your `directory`). Would that do what you want?

That's possible, but for what it's worth, we usually recommend against it. The problem is that it becomes hard to tell which music you've imported already and which still needs to be processed. That's why the guides and the defaults suggest that you keep the two separate. I really do suggest giving this a try, and putting the source and destination both on that external disk—once you've imported everything, then you can remove the old folder and go back to having just a single directory of music.

If you really want to import things in place, I recommend the following workflow: disable `copy` and `move`, which will just leave the files in place (but still fix their tags). Then, when you're all done, type `beet move` to rename everything all at once. This will help avoid confusing situations where properly-named files coexist with some more disorganized files.

**Comment by xpelican** [comment]
Thank you! I had guessed this was a noob question, but for some reason couldn't figure out how to make it happen. Everything works fine now.

For reference to others who may be attempting to do the same thing as I, which was to make the library file also reside on the externally mounted filesystem, basically make your own config file and specify it to beets with the --config=<path to your config file>, then have your script check the target directory variable for your target filesystem, and overwrite the line in your config file specifying library file path with the your target directory path, then launch your operation, as sampsyo explained, with the copy and move options disabled (as specified in your config file) during the import, then doing beet --config <your config file> move -d <target directory>. I also use the -q flag during import to make it completely automated. (you could also, instead of overwriting the line specifying library path in the config file each time, specify the library file in your script dynamically by using beets' global -l option to specify a library file, but for some reason I couldn't manage to create a new library file and have beets accept it was valid afterwards, and this way to have beets create one itself through the config parameters worked.)

Sorry for the late reply, I wasn't able to test this out until now. Thank you once again for your swift and concise answer.

**Comment by sampsyo** [comment]
Great; I’m glad things are working!
