### ISSUE TITLE
[RFE] Add a FAT-sanitizing path function

### ISSUE THREAD

**Issue by mathstuf** [beetbox/beets#3019]
### Problem

When using a plugin like [beets-alternative](https://github.com/geigerzaehler/beets-alternatives) to make "views" of the library (e.g., to copy to a music device), file name may need to be sanitized for FAT filesystems. `%asciify{}` works most of the way, but the following changes also need to be performed:

  - [ ] remove characters `?"|:`
  - [ ] remove trailing spaces and `.` from all path components

**Comment by mathstuf** [comment]
That works on the global library. I only want to do so when dealing with…limited filesystems. Maybe `beets-alternative` should also have a `replace` setting? In any case, such a function might be better anyways so that safe filenames is easier than figuring out all of the oddities with filename rules on FAT.

**Comment by sampsyo** [comment]
It is true that this (sanitizing filenames for safety) is the job of `replace`, not a path function. This is important because sanitation is more complicated than it sounds: for example, what happens if a replacement *introduces* a prohibited pattern in a filename? We need to iterate it to convergence.

I do think that improving the `alternative` plugin would be the right way to go. You might also consider just leaving the `replace` rules as their defaults, which already accommodate FAT conservatively.

**Comment by mathstuf** [comment]
Sounds good. I don't want to leave the rules as the default since I *want* fancy names on my files when the filesystem permits it.
