### ISSUE TITLE
What beets is the?

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [beetbox/beets#3072]
![screenshot_20181104-082656_firefox](https://user-images.githubusercontent.com/14617699/47960373-adcdae00-e00b-11e8-8165-ae865e9d26b1.png)

**Comment by c-e-p-x-u-o** [comment]
It's not fixed. Why have you closed it?

**Comment by sampsyo** [comment]
To be 100% honest, @c-e-p-x-u-o, I closed this issue because it was so impolite. I and other developers on this project sink a lot of unpaid time into working on it, and issues like this—which don't seem to put any effort in to help understand the problem or work toward a solution—can be pretty frustrating in that light.

So please consider opening a pull request if you want to help out. Otherwise, this discussion is over.
