### ISSUE TITLE
In interactive import for tracks, import first the ones that doesn't require user input

### ISSUE THREAD

**Issue by pauser0000001** [beetbox/beets#3119]
When using beet imp . in a directory full of different music, so after a while you select (T) to import them as tracks, you might have more than 50% of them with 100% similarity match that doesn't require user input, but  they are stopped waiting for the ones with low similarity.
My wish is that the tracks that match higher than the default similarity threshold are imported automatically First before human input is needed, and then only the ones that require user input wait for the user to be imported.

**Comment by sampsyo** [comment]
Hi! Have you tried waiting a few moments before diving into the process? The importer uses pipeline parallelism (even for track-based imports), so it should look up subsequent tracks in the background while it's waiting for you to respond to the first prompt.

The fundamental issue here is that we don't know what the similarity is until we fetch the track metadata. You could argue that we just need to reuse the track data from the album match, rather than re-contacting MusicBrainz for each individual track, but that would yield different results: it would constrain each track to be located on that original album match, rather than coming from some other release.
