### ISSUE TITLE
lyrics: Use MusicBrainz artist aliases if default query is not found

### ISSUE THREAD

**Issue by octos** [beetbox/beets#3340]
### Use case

I just noticed that the Lyrics plugin fails to fetch lyrics to [CHVRCHΞS](https://musicbrainz.org/artist/6a93afbb-257f-4166-b389-9f2a1e5c5df8) songs because the artist name contains a Greek uppercase Xi (Ξ), whereas musixmatch.com and lyrics.wikia.com URLs are presumably limited to ASCII characters.

```
lyrics: failed to fetch: http://lyrics.wikia.com/Chvrch%CE%BEs:Forever (404)
lyrics: failed to fetch: https://www.musixmatch.com/lyrics/Chvrch%CE%BEs/Forever (404)
```

### Solution

One solution would be for the Lyrics plugin to cycle through the artist’s [MuzicBrainz aliases](https://musicbrainz.org/artist/6a93afbb-257f-4166-b389-9f2a1e5c5df8/aliases) if it hits a 404 error.

### See also

https://discourse.beets.io/t/asciiized-filenames-for-fetching-lyrics/855

**Comment by sampsyo** [comment]
Sounds good! It's worth noting that the plugin already does a few things like this for normalizing typography, but using the MB aliases would be a good idea too.

**Comment by Moonbase59** [comment]
Now that _is_ an interesting example, since I also have a Chruches album. I mainly use Picard for tagging, and the have two interesting settings under _Options → Metadata_:

[x] Translate artist names to this locale when possible
    [locale dropdown, I selected _English_]
[ ] Use standardized artist names

When I select "Translate", I get "CHVRCHES", when I switch it off, it stays "CHVRCHΞS".
Selecting "Use standardized" seems to change nothing (i.e., it stays "CHVRCHΞS").

Btw, (Album) Artist Sort Order seems always to keep whatever the editor put in "Sort name".

Since Picard is also in Python, it might be worth spelunking in their code to find out how they do it.

**Comment by hashhar** [comment]
I think the better answer is using the sort fields since MusicBrainz encourages (or maybe enforces, not sure) using only ASCII for the sort fields to improve compatibility.

If nobody is currently working on this, I can pick this up after I'm done with https://github.com/beetbox/beets/issues/3549.

**Off-topic:** @Moonbase59 Just in case you were wondering, the "Standardise artist names" means that Artists who get credited with different names on different releases. An example is https://musicbrainz.org/release/1cadc5d0-f4df-4341-aed9-0e33cdc38a72/details which is listed as Release by M.C. Sar & The Real McCoy but it changes to Real McCoy when the config is enabled.

Also, nice to see fellow CHVRCHES fans.

**Comment by hashhar** [comment]
@sampsyo I've got this working. I was not looking to add tests and could figure out the new cases that will go into `LyricsPluginTest.test_search_artist` test cases.

But I can see that there are also some integration tests which make actual network requests to verify things but it looks like they are testing the web scraping part (beautiful soup) instead of the actual plugin logic.

What do you think I should do for this change? Is a new test case which verifies that the `search_pairs` includes the `artist_sort` is enough? Or should I do something else?
