### ISSUE TITLE
Drop Python 3.4 support?

### ISSUE THREAD

**Issue by GuilhermeHideki** [beetbox/beets#3349]
I saw that Python 3.4 has reached [EOL in March 18th, 2019](https://www.python.org/downloads/release/python-3410/) and was wondering if makes sense to drop the Python 3.4 tests now or only in 2020 (after Python 2 EOL)

**Comment by sampsyo** [comment]
Yes, sounds about right to me! And this should probably reopen the discussion about dropping Python 2 support too…

**Comment by slogsdon7** [comment]
The ability to use type annotations would be a nice bonus for dropping support.

**Comment by Moonbase59** [comment]
In principle, I’m all for it, especially since many others (r128gain, MusicBrainz Picard, …) have dropped support for 3.4 already.

_But_ I know a lot of people that still (have to) use Ubuntu 14.04 or Linux Mint 17 and wouldn’t know how to (or dare) upgrade their Python version, since the repos don’t deliver anything new. Then again, adding a little more pressure to upgrade might not be bad, thinking about security alone …

**Comment by GuilhermeHideki** [comment]
Closed by https://github.com/beetbox/beets/commit/bc9e9664fdec77262a9a6047659c8967d6c25a93
