### ISSUE TITLE
Simplified Library Usage

### ISSUE THREAD

**Issue by Vesyrak** [beetbox/beets#3370]
### Use case

I'm trying to use beets to maintain my library, using less metadata than is available.
As in, if I'm trying to import an album, I don't care if it is tagged as a vinyl or a cd from America or a cd from Europe if it's all the same album name, and essentially, the same album.
I just want the correct album name.
Currently, trying to import multiple tracks from the same album causes them to get into "different albums" due to the different release types which I fail to keep selecting consistently.
This causes my music players to treat them as different albums as well, which messes with my album listening experience.

### Solution
Not sure if there is already a solution for this.
I assume I'm not the first one with this use case, but couldn't find any related issues.
Maybe beets doesn't want this use case as it wants as complete as possible tags, something in which I am not interested. In that case I'll look somewhere else ofcourse.

A possible solution could be the ignoring of certain parameters during import, although I'm not sure how viable it is.

Thanks in advance!

**Comment by sampsyo** [comment]
> Currently, trying to import multiple tracks from the same album causes them to get into "different albums" due to the different release types which I fail to keep selecting consistently.

This is actually not the root cause, I think. Even if you selected exactly the same MusicBrainz release, beets would consider them different "albums" for the purpose of tracking in your library. It should, however, offer you the option to merge these albums regardless of which specific release you choose.

Are you seeing the "This album is already in the library!" prompt during import? If you choose to merge the albums then, or just sort them into the same folder ahead of time, you should avoid the problem you're seeing.

**Comment by Vesyrak** [comment]
My apologies for the wait.
You are correct, it seems that this issue has already been resolved, and the albums showing this issue were imported by beets quite a while ago.
Reimporting seems to solve the problem. 

Thanks for your time!
