### ISSUE TITLE
fetchart: Add itunes "high resolution" artwork

### ISSUE THREAD

**Issue by texneus** [beetbox/beets#3391]
### Use case
Use beets to tag, catalog, and fetch artwork.  The FetchArt plugin is enabled to gather album art work.  I have found [this website](https://bendodson.com/projects/itunes-artwork-finder/) that pulls itunes artwork giving the option of both standard (600x600) and hi-res coverart.  The resolution of the high resolution artwork varies, but from what I am seeing is almost always 1500x1500 minimum, and new-ish releases are much higher (for example The Cranberries "In the End" is a 4000x4000).  Besides the size, the artwork is very high quality.

Unfortunately, Beets/FetchArt does not seem to be able to find the high-resolution artwork.  To duplicate, install the FetchArt plugin, and configure FetchArt SOURCES to use only itunes, and set MINWIDTH to 1000.  Verify on the [iTunes Artwork Finder](https://bendodson.com/projects/itunes-artwork-finder/) that high-resolution itunes artwork exists for a target album (for example:  The Cranberries "In the End"), although if there is itunes artwork I have yet to find a case where a high-resolution artwork does not also exist.  FetchArt will fail to find any artwork.

### Solution
Enable FetchArt to fetch high resolution artwork from itunes.  The subject webpage offers his code (in JavaScript and PHP) on GitHub [here](https://github.com/bendodson/itunes-artwork-finder) for examination.

### Alternatives
The only alternative I am aware of is to manually fetch the artwork.

**Comment by sampsyo** [comment]
Sounds great! This seems like a good idea.

**Comment by wisp3rwind** [comment]
Assigned this to myself; however: I will not have time to look at this at least for another month, so if anyone else wants to go ahead, please do so

**Comment by mathieupinet** [comment]
I just had a look at this- it seems the only change would be to fetch an image filename ending with `100000x100000-999` rather than `1200x1200` in fetchchart(as that's what the website cited in the PR retrieves) , in this line as well as L523:
https://github.com/beetbox/beets/blob/9f9af300e8de7be7b1bb6575e4ccb4464fd1ca34/beetsplug/fetchart.py#L513

I succeeded in getting the 4000x4000 _In the End_ cover art with this simple fix, but interestingly the image filesize was 20.7MB (as opposed to 608KB for the 1200x1200 version).

Therefore it probably shouldn't be the default for the iTunes source, as it has wider implications for disk and bandwidth usage than a user would expect?

**Comment by sampsyo** [comment]
Yeah, sounds good! Putting exactly that change behind a config flag seems like the right thing to do.
