### ISSUE TITLE
Keep stock folder names when moving

### ISSUE THREAD

**Issue by BRTPOB** [beetbox/beets#3462]
This is more of a question than a bug report or a feature request (I believe), but basically what I would love to have is the ability to move my music folders to be Artist/Album/Song, but keeping the original folder names. For example:

MP3s
 -Albums
 --Zebrahead
 ---Zebrahead-Get_Nice-2011-MTD
 ---Zebrahead-Live_at_Hurricane_Festival-DVBC-06-24-2012-OMA
 ---Zebrahead-Panty_Raid-2009-COCMP3
 ---Zebrahead-Phoenix-CD-2008-WUS_INT
 ---Zebrahead-The_Bonus_Brothers-Japan_Only_Bonus_Tracks_(2006-2015)-CD-2017-WUS
 ---Zebrahead-Waste_of_Mind-CD-1998-WUS_INT

How can I go about getting beets to keep the original folder names when it does a rename/move?

**Comment by sampsyo** [comment]
Hi! This is not really a built-in feature by any means. The general "beets philosophy" is that _filenames are generated from metadata_. So it should be possible to regenerate the entire directory structure, if necessary, without knowing where files live.

There are a couple of options, however:

- You can imagine writing a custom plugin that assigns some special metadata fields based on the original filenames. You might have something like `$album_extra` or something that keeps strings like `2011-MTD` or `DVBC-06-24-2012-OMA`. Then use `$album_extra` in your path formats. This could be really nice because it would let you change this metadata later and keep your paths in sync. Or you could query albums using this string, if it's meaningful to you.
- You could do some weird magic with the `inline` plugin that uses the `$path` field to generate a pseudo-field based on the current path. This is a bit more fragile but wouldn't require spinning up your own plugin.

You could started with the first approach without writing a custom plugin by setting the field manually with `beet modify album:'get nice' album_extra='2011-MTD'` or similar.
