### ISSUE TITLE
original_{year,month,day} should probably only count Official releases

### ISSUE THREAD

**Issue by emilazy** [beetbox/beets#3475]
I have a path configuration including the original date, which leads to an official release of [Extraordinary Machine](https://musicbrainz.org/release-group/81c98a74-56ba-355e-8d63-83e12a63dace) being filed under the directory `Fiona Apple/2005-03 Extraordinary Machine`, the date of the Bootleg-classed leak of an alternate version of the album, rather than its official release date of 2005-10-03.

I'm not sure whether this is something that could be resolved in beets or if it's an upstream MusicBrainz infelicity, but I figured I'd file it to find out.

**Comment by sampsyo** [comment]
Huh, thanks for pointing this out! We currently use the `first-release-date` property of the release group as reported by MusicBrainz:
https://github.com/beetbox/beets/blob/ca3142b1d92d177a2d789775a4ff2ee5569b9ba6/beets/autotag/mb.py#L383

For example, see the [the JSON data for that album](http://musicbrainz.org/ws/2/release-group/81c98a74-56ba-355e-8d63-83e12a63dace?inc=artist-credits+releases&fmt=json), which faithfully reports the earliest release date without any regard to status.

We could consider _not_ using this field and instead search for "official" releases, but it may be more complicated than that—for example, we'd have to figure out which list of statuses to respect, and some release groups have no official releases. It would be awesome if this could be resolved on the MB side so we can rely on them to make the "right" choices here, but I can anticipate that that might not really be feasible (e.g., some software might depend on the current behavior). So maybe it's worth starting a dialog with the MB people and falling back to a beets fix if that turns out to be the right thing?

**Comment by emilazy** [comment]
I've reported this [upstream on MetaBrainz](https://tickets.metabrainz.org/browse/MBS-10626).

**Comment by jtpavlock** [comment]
I think for this one it's probably best to wait for a decision from musicbrainz before acting. @djl did you have something else in mind?

**Comment by djl** [comment]
Don't remember re-opening this. Must've fat fingered the re-open button on my phone :(
