### ISSUE TITLE
Feature Request: Expand Audio Types

### ISSUE THREAD

**Issue by JoshuaFern** [beetbox/beets#3539]
### Use case

I'm trying to use beets to categorize more than just standard MP3 or FLAC audio, here's some examples of the files in my collection:
* MIDIs, like music from [VGMusic](https://www.vgmusic.com/)
* SIDs, like music from the [High Voltage SID Collection](https://www.hvsc.c64.org/)
* Trackers, like music from [KEYGENMUSIC](http://keygenmusic.org/)

I also have a lot of spoken word audio, for example:
* Lectures
* Podcasts
* Audiobooks

It would be nice to categorize these as well.

### Solution
Implement support for additonal filetypes, related: #1935

Many of these filetypes probably have limited metadata and would rely heavily on file and folder names. The good news is many of the sources I listed above already do a decent job at categorizing and naming files correctly.

### Alternatives
I couldn't find any official documentation on what do do with spoken word but I've deduced it might be doable using `paths`

I propose adding a section on spoken word to the beets.readthedocs.io

**Comment by sampsyo** [comment]
Hi! Thanks for the input… it sounds like there are several different threads of discussion here.

We can always consider adding more file types, but it's generally important for those first to be supported by [Mutagen](https://mutagen.readthedocs.io/en/latest/), the underlying tag-manipulating library that beets relies on. Maybe investigating what metadata storage looks like for those formats would be a good place to start?

Separately, you mentioned:

> I also have a lot of spoken word audio, for example: […] It would be nice to categorize these as well.

Which is a different category of request. Those aren't *file formats* like MP3, FLAC, or MIDI—they're just different *purposes* you might use an audio file for. Because audiobooks might be stored as MP3s, for example, it seems like you can already catalog these things with beets.

Can you elaborate on what is currently missing from beets, from your perspective, to "support" these kinds of uses for audio?

**Comment by JoshuaFern** [comment]
I thought about it a little more,

For the case of the spoken word audios, my idea is to create an alias 'beets_sw' with the `--config` option to a second config, folder, and database just for spoken word. This should work a lot better than trying to combine music and spoken word, especially because the configuration for spoken word looks a lot different!

In the case of MIDIs, SIDs, and Tracker files I believe there's probably no reason for beets to support these as they don't seem to contain any metadata. I'll just keep them separate for now. Perhaps I could simply convert these to MP3s.

**Comment by sampsyo** [comment]
Sounds great! Thanks for the thoughts.

**Comment by wisp3rwind** [comment]
Note that you can already discriminate in the configuration between spoken word and music by using queries on the `albumtype` field, e.g.
```
paths:
    albumtype:audiobook: audiobooks/$artist - $album%aunique{}/$track - $title
    albumtype:soundtrack: soundtracks/$album%aunique{}/$track - %the{$artist} - $title
    default: music/%the{$albumartist}/$album%aunique{}/$track - $title
```
