### ISSUE TITLE
web plugin: Can't do path queries

### ISSUE THREAD

**Issue by nmeum** [beetbox/beets#3566]
### Problem

The beets web plugin provides a [JSON API](https://beets.readthedocs.io/en/stable/plugins/web.html?highlight=web#json-api). This JSON API has a `/item/query` endpoint. Using this endpoint I want to perform a [path query](https://beets.readthedocs.io/en/stable/reference/query.html#path-queries). For example:

```
path:/home/nmeum/music/Singles
```

Unfortunately, such path queries do not work with the JSON API due to the `QueryConverter` which is used for the `/query` endpoint:

 https://github.com/beetbox/beets/blob/d43d54e21cde97f57f19486925ab56b419254cc8/beetsplug/web/__init__.py#L175-L183

This class converts the query from above to:

```
path:home,nmeum,music,Singles
```

which obviously does not work as intended. It doesn't make a difference whether the path query is URL encoded or not. Maybe this could be fixed by invoking the `QueryConverter` before URL decoding is performed? Additionally, it seems that the `QueryConverter` behaviour is not actually documented in the JSON API doc.

This issue cannot be workaround by using the `/item/path/...` endpoint, because this endpoint returns a different JSON document.

See also: https://github.com/pallets/flask/issues/900

### Setup

* OS: Alpine Linux
* Python version: 3.8.2
* beets version: 1.4.9
* Turning off plugins made problem go away (yes/no): N/A

**Comment by sampsyo** [comment]
Hi! Thanks for pointing this out!

To explain a little more, the reason it works this way is actually not because of the introduction of the implementation of QueryConverter in 004e9a8144cd120f6f245dd9865db469c243d34d, which just does a nicer (and bidirectional) implementation of the same behavior that existed before using `query.split('/')`.

Basically, the idea with the original URL design was that `http://example.com/music/item/query/artist:foo/album:bar` would be the way you'd query for tracks with a given artist and album. In a true RESTful style, one query would be "contained" within another—the set of tracks for the "subdirectory" would be a subset of the tracks in the "superdirectory."

However, I agree that this didn't really pan out and there's no particular need for the query to be organized in a fake RESTful hierarchy like that. And obviously it's inconvenient if you actually want to include a literal slash in the query.

However, as I'll comment on the PR shortly, we'll want to make sure that removing this kind of endpoint doesn't break anything…
