### ISSUE TITLE
Album art is being indexed in database but not Album path ?

### ISSUE THREAD

**Issue by chromafunk** [beetbox/beets#3604]
I just finished indexing my first large music db and while exploring the database schema, I am realizing the album path is not being indexed, but only the album art path. Is there a way I can re-index without tagging in order to get a database that includes the album path ? I can see that it does index the individual tracks path, but not the album path ?

Thanks

**Comment by sampsyo** [comment]
Sorry, no—the beets database does not try to keep track of any notion of an "album path." Only the files actually have paths, and _if the user decides to_, they can exist in a common directory. However, beets does not require this—you can sort all your tracks by artist or whatever, in which case there is no directory that could be reasonably called an "album path."

Within beets, there is a thing called `album.path`, which is beets's best guess at the directory for the album—at the moment, this is just the directory containing the first track. But this does not appear in the database.

**Comment by chromafunk** [comment]
Thanks, on this case I would suggest adding it to the album schema if beets can guess it

**Comment by sampsyo** [comment]
Unfortunately, I don't think that's feasible. Adding derived data like that to the database introduces consistency headaches—it's not just a matter of putting the data there in the first place; we will need to detect when it goes out of date and keep it synchronized. And for beets's own purposes, we don't need it—it's easy to just recalculate derived data like that. Furthermore, we may later come up with better ways of approximating the "album directory" idea, for example—which would then require something like a database migration to update the stale information.

Are you doing something where you interact with the SQLite database directly rather than using beets itself?
