### ISSUE TITLE
Playing albums or playlists via web

### ISSUE THREAD

**Issue by darakian** [beetbox/beets#3609]
### Use case

I'm trying to use beets as a music server with the webUI being the primary interface

### Solution
Extend the web interface to search on albums/artists/etc and to either continue playing on the current selection or to build playlists. For my use case playing albums is sufficient.

### Alternatives
I'm not aware of any, but maybe they exist.

**Comment by sampsyo** [comment]
Hi there! This sounds cool but the web thingy is really meant as a bare-bones demo rather than a full-featured music player. I think the right medium-term solution here is to stop shipping our own player and instead rely on [AURA](https://github.com/beetbox/aura) to let innovation in the UI happen separately.

See also #718 and #738 for a vision for more full-fledged players.

**Comment by darakian** [comment]
Oh cool. I'll check into those. For what it's worth I really like the minimalism of the built in web player. Either way I'll keep an eye on things. Thanks for the work :)
