### ISSUE TITLE
Fetch/embed art for single tracks

### ISSUE THREAD

**Issue by Clouraxe** [beetbox/beets#3633]
### Use case

Id like to fetch art by track if thats possible, as I dont use albums

### Solution

Maybe add `-s` option to `fetchart` to search by track just like the import, itd be quite handy

**Comment by sampsyo** [comment]
Please see #132.

**Comment by Clouraxe** [comment]
Im sorry, still new here, but I dont really see a solution in there? its just the same issue discussed...

**Comment by sampsyo** [comment]
Yep, no solution in there! That’s just where we are tracking this feature request. As with most open-source projects, we close duplicate issues so the discussion stays focused. It’s generally a good idea to search for existing issues where you can add your thoughts, if possible, instead of opening new ones.

**Comment by Clouraxe** [comment]
Ah, I see.
Thank you for your kindness :)
