### ISSUE TITLE
import return codes

### ISSUE THREAD

**Issue by starenka** [beetbox/beets#3726]
I'm automating my new arrivals pipeline and it's kinda hard to distinguish if `beet imp /something -q` actually imported something or skipped the album. As the imp command does always (afiak) returns `0` RC, I'm parsing the output like `if [[ "$resp" == *Skipping. ]]; then`. It seems that the output is sometimes buffered or butchered in some other way, so the `skipping` string is not always at the end. 

Do you think adding non zero rcs for `-q` import error states would be feasible (not good match, already in, etc)? Cheers.

**Comment by sampsyo** [comment]
Yo! We do have an issue generally about discussing more useful return codes in #539. In general, stuff like this would be great, but it's surprisingly hard to do because beets is usually in batch mode (not just importing a single album). Something good to discuss in that thread, for example, would be what the return code should look like if some imports "succeed" (for some definition of "succeed") and some "fail" (for some definition of "fail).

**Comment by starenka** [comment]
Yeah, i read the issue before making this one. It was about an overkill (imo) for ls command, that's why i emphasised the import stuff. 

Frankly, whats the problem to return it during import, even in batch mode? I recognize it's not an easy decision, but well even in batch mode you can be announced, not all stuff was imported...

**Comment by sampsyo** [comment]
Indeed, it's not a problem to do—but we do have to decide what to do. Does one skipped album flip (of hundreds) flip the code from 0 to 1? Does it matter if it's a skip the user requested? Is there a difference for incremental-mode automatic skips vs. quiet-mode skips? Etc.
