### ISSUE TITLE
autofilling random album smartplaylist.

### ISSUE THREAD

**Issue by johnappletree** [beetbox/beets#3799]
Long time beets user here, using the software on a daily base. Big thanks to the Maintainers!

### Use case

I am looking for an option that plays entries albums and automatically queues an (entire) related album afterwards. This would prevent my music from stopping.

I was thinking of doing this with smart playlists. 
Would this behavior be scriptable with smart playlists? I tried to get my head around it but could not figure out how to add entire albums without shuffling them.

**Comment by sampsyo** [comment]
Hi! That sounds interesting. I'm not entirely sure about the whole "find a related album" aspect, but one piece of the `smartplaylist` plugin that might be helpful is the `album_query` option for a given playlist. That lets you query for entire albums instead of individual tracks.

Beyond this, it might be worth starting a longer discussion [on the Discourse](https://discourse.beets.io) about what you're interested in. It might involve tying things together with another player app, for instance.

**Comment by johnappletree** [comment]
Thanks I will have a look at that later tonight. Is there something like sort random, to select a random album?

**Comment by sampsyo** [comment]
Not exactly, although there is a `random` plugin. The https://github.com/beetbox/beets/issues/795 thread might be interesting to yuo.

**Comment by johnappletree** [comment]
Would be cool if I could query random:5 in the smartplaylist plugin. Unfortunately I did not achieve what I was looking for. Closing this issue anyway.
