### ISSUE TITLE
Rewrite more of beets in Cython

### ISSUE THREAD

**Issue by dertuxmalwieder** [beetbox/beets#3821]
### Use case

I'm trying to use beets to manage my music library. It works really well, but I still think that it could be faster. I know that Python is a bottleneck when it comes to performance, but after having spent some time trying to understand how Cython works, I wonder if it would make sense to use more Cython code in beets. I know that beets uses quite some Cython'ized libraries - but this repository mainly has .py instead of .pyx files.

Just an idea.

**Comment by wisp3rwind** [comment]
I'm pretty sure that there's not much to be gained by using Cython. I've never used Cython, though. Beets is slow due to inefficient database usage and insufficient IO parallelism, none of which are issues that Cython would help with. As far as I know, essentially no CPU-bound work is done by beets directly. There are some ideas to improve the importer pipeline to drive IO more efficiently. I'm not sure there are any concrete ideas to speed up database access. The proper start here would be to do some profiling (there might be some open Github issues in this regard).

Closing this for now. If there's any specific component in beets that could profit from Cython, feel free to reopen (or better create a new issue). Otherwise, I don't see much of a point in discussing abstractly whether or not we want to allow Cython code.

**Comment by sampsyo** [comment]
Thanks for the the explanation, @wisp3rwind. Cython is cool and it's a fun idea but it's not practical—the "low hanging fruit" for speeding up beets would be optimizing queries, removing bottlenecks found by profiling, etc. And those have the benefit of not requiring a native C compiler to build & install beets (which using Cython would).
