### ISSUE TITLE
How to auto compute the fingerprint with autotag=no?

### ISSUE THREAD

**Issue by ribeaud** [beetbox/beets#3853]
### Use case

This feature request is a follow-up of #3417. I am not interesting in `autotag`. My library is pretty clean and I am strict regarding _tagging_.

Additionally, all the **beets** computed information is stored in the database, I do not want **beets** writing tags to my original files.

However, I would appreciate if  **beets** auto-computes the fingerprint. Obviously and up to the answer posted in #3417, this will not happen because `autotag` is deactivated on my end. 

### Solution

Either compute the fingerprint if `auto` is set. This flag is otherwise useless if `autotag` is set to _no_. Or provide a _force_ option?

Another possibility would be to have a dedicated `fingerprint` configuration section, probably the cleanest solution...

**Comment by sampsyo** [comment]
Just to confirm, you are not looking for the solution of running `beet fingerprint` explicitly after import?

Otherwise, I think this is a broader issue and not just about this one plugin. We would need to restructure things in such a way to allow plugins to possibly run even in non-autotagging mode (while also providing a way for them to be disabled, probably by default).

**Comment by ribeaud** [comment]
Hi @sampsyo. Thanks for your reply. Correct.

**Comment by sampsyo** [comment]
Got it. Could you please add to the discussion in #726, which probably should be reopened (I'm not sure why @Kraymer closed it)? That covers the more general issue about what to do regarding `auto` plugins in the absence of autotagging.
