### ISSUE TITLE
Song filenames corrupted on import

### ISSUE THREAD

**Issue by afonsoguerra** [beetbox/beets#3884]
After creating a set of FLAC files from scratch from a fairly large box set, I used Beets to add it to my library. The resulting filenames are mangled and have endings like: .flacvogelgesaoF

The album in question is:
https://musicbrainz.org/release/908ecf81-20e9-4c87-ba15-7c746d72743f

I suspect the problem might be related to badly sanitised carriage returns somewhere. 

Is there an easy way to change beets to detect these problems and automatically clean the metadata / name the files sensibly on move?

Thanks!

**Comment by sampsyo** [comment]
Hello! When you report a problem, it *really* helps us if you use the issue template. I know it looks like a lot of extra information, but actually including the verbose output from running the command and your versions can help us understand what's happening.

Since this is a pretty mysterious-sounding problem, it would be really helpful if you could help us reproduce the problem, somehow.

**Comment by afonsoguerra** [comment]
beets version 1.4.9
Python version 3.6.9
plugins: acousticbrainz, bpd, chroma, duplicates, embedart, fetchart, lastgenre, lyrics, missing, replaygain, web


I don't have the original files to re-run from scratch. Once I re-encode the CDs I'll get back to you. Will keep a copy this time! There was no obvious message to say this had been corrupted, I just found today that the files were not named as I was expecting. I did not come across the issue template when looking to see if anyone else had the same problem, sorry.

**Comment by afonsoguerra** [comment]
Is there any code sharing between Beets and Picard?

I have just attempted to re-tag a fresh copy of the album with Picard and the same problem occurs, further supporting my suspicion this has to do with the upstream information in MusicBrainz DB. 

Final question, is there an easy way to dump the information that Beets is getting from MusicBrainz to try to debug this?

At the moment I don't think this is a bug, but rather a feature request to sanitise input so that the problem filenames do not happen.

**Comment by wisp3rwind** [comment]
> Is there any code sharing between Beets and Picard?

Maybe some library shared by both? None that I know of, but the autotagger is not a part of beets of that I know much about, and I'm not familiar with Picard at all.

> I have just attempted to re-tag a fresh copy of the album with Picard and the same problem occurs, further supporting my suspicion this has to do with the upstream information in MusicBrainz DB.
> 
> Final question, is there an easy way to dump the information that Beets is getting from MusicBrainz to try to debug this?

I don't think so (again, I'm not certain). But as @sampsyo said, a first step would be to run the command with beets in verbose mode (`beet -vv ...`) and report the full output here. Ideally, try reproducing the issue with plugins disabled. And, specific for this issue, I think it might be useful if you pasted the full, mangled filenames. Maybe, a pattern can be spotted there. Please, also provide the full beets configuration.

With the amount of details that you've provided up to now, we're unfortunately only poking in the dark.

> At the moment I don't think this is a bug, but rather a feature request to sanitise input so that the problem filenames do not happen.

I would say that this sounds like a bug, whatever the underlying issue is. One thing that sticks out on MB is that these titles have extremely long names (such as https://musicbrainz.org/recording/95f63e50-147a-4067-baa9-1c8d1daadfdd). Maybe some library makes invalid assumptions here?

**Comment by sampsyo** [comment]
One other thing to try if you're seeing the same behavior in beets and Picard: could it be that the filenames are "correct" and just look wrong with whatever software you're using to view them (e.g., `ls` in your terminal or your GUI file manager)? Could be worth double-checking with some other way to view the filenames.

**Comment by afonsoguerra** [comment]
Apologies all, I thought I had closed this a long time back. After further experimentation, I've figured that the file extensions were getting corrupted probably upstream of beets and beets was just propagating the error. Because of my archival practices (files get moved, so originals get destroyed) and that the problem only was apparent after beets, I wrongly assumed beets was to blame, since it was editing the metadata and filenames.
