### ISSUE TITLE
Beets hangs at Sending event: import_task_choice, with no prompt

### ISSUE THREAD

**Issue by axujen** [beetbox/beets#3955]
### Problem

Running this command in verbose (`-vv`) mode:

```sh
$ beet -vv import .
```

Led to this problem: https://pastebin.com/wfyaJ8Jt

the script simply hangs at Sending event: import_task_choice with no prompt no nothing, i tried with my personal config and a no config and its the same.
i tried it in zsh and bash and nothing.

idk if this is a duplicate, if some close it, but searching for Sending event: import_task_choice has 72 issues

### Setup

* OS:  Manjaro
* Python version:  3.9.4
* beets version: 1.5.0
* Turning off plugins made problem go away (yes/no): no

My configuration (output of `beet config`) is: Empty configuration

**Comment by wisp3rwind** [comment]
This one's weird. beets did show the prompt for selecting one of the musicbrainz matches, right? Which action did you choose in that prompt?

>     * beets version:

Your exact beets version would be important to know (i.e. the git commit id). Did this issue only pop up after a recent update?

**Comment by axujen** [comment]
> This one's weird. beets did show the prompt for selecting one of the musicbrainz matches, right? Which action did you choose in that prompt?

No, i get no prompt, also sorry i forgot about the beets version, ill edit it in.

**Comment by wisp3rwind** [comment]
> > This one's weird. beets did show the prompt for selecting one of the musicbrainz matches, right? Which action did you choose in that prompt?
> 
> No, i get no prompt, also sorry i forgot about the beets version, ill edit it in.

That's a development version, can you also look up the exact git revision? How did you install beets? Given that the import_task_before_choice event is not included in the logs, this cannot be the current git tip, but must be older than ~march 2021.

Since beets is hanging, I suppose you aborted it using CTRL-C? Did Python print a traceback that you could share?

**Comment by axujen** [comment]
https://pastebin.com/RwpmYEiU for python traceback

i installed beets from the manjaro community repo
its beets-1.4.9.r1031.cbc045f1c-1
idk why it says beets 1.5.0 when i use --version, i also dont know where to find the exact commit but i dont think its a git build

**Comment by wisp3rwind** [comment]
> https://pastebin.com/RwpmYEiU for python traceback

Unfortunately, there's no useful info in there...

> i installed beets from the manjaro community repo
> its beets-1.4.9.r1031.cbc045f1c-1
> idk why it says beets 1.5.0 when i use --version, i also dont know where to find the exact commit but i dont think its a git build

It is, because we haven't had an actual release in quite a while. Some distributions have moved their packages to a development version, including manjaro as it appears. `cbc045f1c` is the commit id.

> i just installed the beets-git package from the aur and i get the same issue.

Please also post the `beets -vv` log, it might be slightly different.

**Comment by axujen** [comment]
> Please also post the `beets -vv` log, it might be slightly different.

https://pastebin.com/jVXWcQWB for the git version

**Comment by sampsyo** [comment]
Weird. I am pretty mystified about what could be going on there. Maybe it would be worth trying the import with threading turned off:
https://beets.readthedocs.io/en/stable/reference/config.html#threaded

…and see if the behavior or traceback is any different?

**Comment by axujen** [comment]
> Weird. I am pretty mystified about what could be going on there. Maybe it would be worth trying the import with threading turned off:
> https://beets.readthedocs.io/en/stable/reference/config.html#threaded
> 
> …and see if the behavior or traceback is any different?

yup, that fixed it

**Comment by sampsyo** [comment]
Pretty strange!! I remain mystified about why threading would hide that output on your system. It seems clear that the problem is some sort of synchronization deadlock in the underlying pipeline implementation, but it's really hard to say exactly where it's coming from without a way to reproduce the problem.

Maybe sprinkling in a million `print` statements throughout the stages in `importer.py` could help indicate where things are hanging?

**Comment by axujen** [comment]
> Pretty strange!! I remain mystified about why threading would hide that output on your system. It seems clear that the problem is some sort of synchronization deadlock in the underlying pipeline implementation, but it's really hard to say exactly where it's coming from without a way to reproduce the problem.
> 
> Maybe sprinkling in a million `print` statements throughout the stages in `importer.py` could help indicate where things are hanging?

more importantly why is the problem happening only to me?

**Comment by wisp3rwind** [comment]
> Pretty strange!! I remain mystified about why threading would hide that output on your system. It seems clear that the problem is some sort of synchronization deadlock in the underlying pipeline implementation, but it's really hard to say exactly where it's coming from without a way to reproduce the problem.
> 
> Maybe sprinkling in a million `print` statements throughout the stages in `importer.py` could help indicate where things are hanging?

I doubt that the pipeline is directly involved: According to the plugin events in the log, the hang happens within a single stage (`user_query`), in between
```
Sending event: import_task_choice
Sending event: import_task_apply
```

The traceback simply doesn't seem to include all threads.
