### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by haby0** [beetbox/beets#4111]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by haby0** [comment]
@sampsyo Hello, can I disclose the details of the vulnerability fix and apply for CVE?

Reference: https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories

**Comment by sampsyo** [comment]
I have no objection in principle. But could you perhaps clarify what work/responsibilities this would require of the project maintainers?

**Comment by haby0** [comment]
> I have no objection in principle. But could you perhaps clarify what work/responsibilities this would require of the project maintainers?

Just create a security advisory here (https://github.com/beetbox/beets/security/advisories), then publish the advisory and apply for CVE.

Creating a security advisory: https://docs.github.com/en/code-security/security-advisories/creating-a-security-advisory

Publishing a security advisory and apply for CVE: https://docs.github.com/en/code-security/security-advisories/publishing-a-security-advisory

Example: https://github.com/aimhubio/aim/security/advisories/GHSA-8phj-f9w2-cjcc

**Comment by sampsyo** [comment]
OK! Maybe you could help out by writing up the description for the disclosure filing?

For that, I think a super useful step to make things more concrete would be to demonstrate a proof of concept. As I mentioned in the message for #4160, I'm actually not 100% clear on whether this is exploitable—namely, it seems like you would want to construct an `img_filename` like `../foo/bar.txt`, but I don't think the Flask URL parser would allow slashes in the chunk of the URL denoted by the `<string:image_id>` pattern. So maybe a little more homework to demonstrate/describe exactly how this works would be helpful for the process?

**Comment by haby0** [comment]
Ok.
In addition to ../, directory fallback characters also have ..\

**Comment by haby0** [comment]
## Description

### Impact
A path traversal attack aims to access files and directories that are stored outside the web root folder. By manipulating variables that reference files with “dot-dot-slash (../)” sequences and its variations or by using absolute file paths, it may be possible to access arbitrary files and directories stored on file system including application source code or configuration and critical system files.

Vulnerable code:

**Comment by haby0** [comment]
@sampsyo After applying for CVE, Github Security lab will review the validity of the vulnerability.

```md
### Description

#### Impact

Path traversal attacks are designed to access files and directories stored outside the root web folder. By operating variables that refer to files with the "..\\" sequence and its variants, you can access any files and directories stored on the file system, including application source code or configuration and key system files.

Vulnerable code: 

https://github.com/beetbox/beets/blob/92b6d7ea7ce5ba30be111d38fdbf835ca7e23317/beetsplug/aura.py#L862-L879

https://github.com/beetbox/beets/blob/92b6d7ea7ce5ba30be111d38fdbf835ca7e23317/beetsplug/aura.py#L605-L640

#### Patches
The vulnerability issue is resolved in Beets v1.6.0.

#### References
https://owasp.org/www-community/attacks/Path_Traversal

```

**Comment by sampsyo** [comment]
As I mentioned above, can you please include a proof of concept, i.e., a concrete example of a path that you have tried requesting and which demonstrates an out-of-directory read?

**Comment by haby0** [comment]
curl -v http://host/images/album-1-..\\..\\..\\file/file

**Comment by sampsyo** [comment]
Hi, @haby0—have you actually tried out this request in a running server? As I asked above, it would be really useful to see a _demonstration_, i.e., an execution showing Flask actually parsing this URL and actually generating a "bad" filename.

In particular, I think your example only works on Windows? Is that the case? I don't think other OSes interpret `\` as directory separators. If so, maybe this is worth mentioning in the disclosure?

(This is why I have been asking for an actual, concrete demonstration instead of just high-level output from a static analysis tool. It seems important to do some digging to understand exactly what is possible and how so we can put actionable, truthful information in a disclosure.)

**Comment by haby0** [comment]
> Hi, @haby0—have you actually tried out this request in a running server? As I asked above, it would be really useful to see a _demonstration_, i.e., an execution showing Flask actually parsing this URL and actually generating a "bad" filename.
> 
> In particular, I think your example only works on Windows? Is that the case? I don't think other OSes interpret `\` as directory separators. If so, maybe this is worth mentioning in the disclosure?
> 
> (This is why I have been asking for an actual, concrete demonstration instead of just high-level output from a static analysis tool. It seems important to do some digging to understand exactly what is possible and how so we can put actionable, truthful information in a disclosure.)

Great. I first tested it on Windows, and the problem is there.

In addition, I just conducted a fuzz test on Linux, and the problem does not exist on Linux.

**Comment by sampsyo** [comment]
Those are both intriguing statements—do you think you could provide more details on both of those? For example, actual terminal output from the Windows execution could be great. And I don't exactly see how fuzzing would apply here—which fuzzer did you use, with what configuration, etc.?

**Comment by haby0** [comment]
I think this is enough detail. Fuzzing in Linux: Path Injection.

**Comment by sampsyo** [comment]
From @haby0 via email:

> Text proof. 
>
> There is no local proof that the vulnerability exists, I will not send it to you, it will not do me any good...
> 
> [Path injection of Flask String type under Windows.docx](https://github.com/beetbox/beets/files/7627365/Path.injection.of.Flask.String.type.under.Windows.docx)

The attachment appears to consist of screenshots of a small Flask app handcrafted to show a path injection vulnerability. It is not a demonstration in beets itself. It does, however, seem to suggest that backslashes are enough to craft an out-of-directory read specifically on Windows.

Anyway, I guess we can take it from here. @haby0, while we appreciate your report, this has been an extremely difficult process because of how hard it has been to get details and cooperation from you. I'm not sure you're aware of this, but your messages have been vague and very short on details, which makes it really hard to take action based on your input. You seem to have some motivation that is not aligned with helping the project; perhaps there is some incentive to file CVEs even without deep understanding of the underlying problem. I need to respectfully ask you to disengage at this point; the maintainers may be able to get around to creating the vulnerability report, but it may take some time. Additional "bumps" to remind us to do so will not be helpful.
