### ISSUE TITLE
Disconnect album_info.va from item.comp

### ISSUE THREAD

**Issue by snejus** [beetbox/beets#4295]
Currently, every album which has `va = True` has `COMPILATION` Vorbis field set to 1 (at least for tracks that have FLAC format), which is not always correct. 

As per [MB Special purpose artist guidelines](https://beta.musicbrainz.org/doc/Style/Unknown_and_untitled/Special_purpose_artist), __Various Artists__ albumartist should be used for _compilation-type releases **or** release groups containing tracks by multiple different artists_, - the latter applies to albums and EPs also. Also see [MB compilation secondary type guidelines](https://beta.musicbrainz.org/doc/Release_Group/Type).

From the metadata sources plugin developer perspective, it seems that the `va` field should say whether the album is by a single or multiple artists and it should not influence any decision making to do with the album type. 

For reference, snippet from `autotag/match.py`:
```python
        # Is this album likely to be a "various artist" release?
        va_likely = ((not consensus['artist']) or
                     (search_artist.lower() in VA_ARTISTS) or
                     any(item.comp for item in items))
```

and `autotag/__init__.py`:
```python
        # Compilation flag.
        item.comp = album_info.va
```

**Comment by sampsyo** [comment]
Huh, that's an interesting issue! You seem to be right that we're not mapping the `comp` flag in beets (and in MediaFile) precisely to compilation-type releases.

I think this is a little tricky because the current semantics of the `comp` flag are a match for common use scenarios. For example, the default path format configuration creates a special directory for compilations (according to this flag, including other VA releases that are not "compilations" in MB's parlance). This is nice because it means there is not a separate "Various Artists" directory separate from the "Compilations" directory.

So if we investigate this change, at the very least we'd want to invent and support another, broader field that has the same semantics as the current `comp`. However, this would be a somewhat disruptive change. And people who want to select _only_ compilation-type releases can already use the query `albumtype:compilation`. So I'm not yet entirely sold on the idea that the benefits outweigh the costs, despite the clearer adherence to MB guidelines.

**Comment by snejus** [comment]
This makes a lot of sense, @sampsyo. I now remember that `comp` is used in the default paths configuration:
```yaml
paths:
    comp: Compilations/$album%aunique{}/$track $title
```
so I do agree about the change being disruptive.

It actually isn't an issue at all: I've just checked what's being returned from MusicBrainz for some split EPs and EPs by Various Artists and it all seems to be reasonable. I correct myself here:
~~From the metadata sources plugin developer perspective, it seems that the va field should say whether the album is by a single or multiple artists and it should not influence any decision making to do with the album type.~~

It seems that the use of `comp` is mostly internal and thus it's fine. :)
