### ISSUE TITLE
Tekstowo lyrics source needs to be adapted to new website layout

### ISSUE THREAD

**Issue by wisp3rwind** [beetbox/beets#4334]
From #4228
> That's probably the same thing that makes our weekly integration tests fail, cf. e.g. https://github.com/beetbox/beets/actions/runs/2046155673 
>
> The Tekstowo source needs to be fixed; I guess they updated their website structure at some point and our scraper now picks up extraneous text?
>
_Originally posted by @wisp3rwind in https://github.com/beetbox/beets/issues/4228#issuecomment-1085073680_

**Comment by qcasey** [comment]
Googling this issue brought me here. I think this was fixed in https://github.com/beetbox/beets/commit/3f896ab28117cd9032a0d9fcc8fc5c871f954324? I use Tekstowo a lot.

### beets 1.6.0

Tracks with extraneous text:

```
$ beet stats "lyrics:Tekst piosenki:" 
Tracks: 2716
Total time: 1.1 weeks
Approximate total size: 14.2 GiB
Artists: 988
Albums: 562
Album artists: 531
```

### beets master/1.6.1

Switched to the git version of beets:

`pip3 install git+https://github.com/beetbox/beets`

Reran `lyrics` on tracks with extraneous text:

`beet lyrics "lyrics:Tekst piosenki:" `

Lyrics look right now.

```
$ beet stats "lyrics:Tekst piosenki:"
Tracks: 0
Total time: 0.0 seconds
Approximate total size: 0.0 B
Artists: 0
Albums: 0
Album artists: 0
```

**Comment by wisp3rwind** [comment]
See #4344: Probably there's no issue, but a report based on an old version of beets. Feel free to re-open or create a new issue if this is not true.
