### ISSUE TITLE
Info language settings

### ISSUE THREAD

**Issue by antonellocaroli** [beetbox/beets#4366]
Hi,

in the import section I set 
`languages: en de it`

it seems to work for the artist name, but the album name always imports it in the original language.

maybe i need to change something else in the settings file?

before:

![Selezione_187](https://user-images.githubusercontent.com/11161093/173184631-ce59f2ad-d47d-4c4f-af52-504aa6dad470.png)

after:

![Selezione_188](https://user-images.githubusercontent.com/11161093/173184885-3eb200fd-2731-4987-adcb-5376583e123b.png)

**Comment by sampsyo** [comment]
Hello! When you report a problem, it *really* helps us if you use the issue template. I know it looks like a lot of extra information, but actually including the verbose output from running the command and your versions can help us understand what's happening.

**Comment by jackwilsdon** [comment]
Assuming your issue is with "Komitas" becoming "Կոմիտաս", that is one of the album artists and not the name of the album (the album is called "Hayren").

If you check the [MusicBrainz aliases](https://musicbrainz.org/artist/01fbf8ab-34e2-4a0a-8dcc-8d9a8026d782/aliases) for this artist, they currently don't have an "English" alias:

![Կոմիտաս aliases on MusicBrainz](https://user-images.githubusercontent.com/1843197/173189168-17a036ce-9b3a-4fbc-809c-d138a5049240.png)

Compared to [Տիգրան Մանսուրյան](https://musicbrainz.org/artist/247c80ca-393f-4f07-b245-b9fc9d795976) (note the "Typename " and "Locale" fields):

![Տիգրան Մանսուրյան aliases on MusicBrainz](https://user-images.githubusercontent.com/1843197/173189180-50c0f863-2542-487c-b673-c96f571c69a4.png)

Your best option here is to sign up for a MusicBrainz account and edit the "Komitas" alias, setting the locale to "English" and the type to "Artist name", which should allow beets to pick up this translation (there may be a short delay after editing before beets picks it up due to caching on MusicBrainz's side).

As this is a data issue on MusicBrainz, I'm going to go ahead and close this.
