### ISSUE TITLE
Add the ability to handle error 429 (too many requests) in Spotify plugin

### ISSUE THREAD

**Issue by arsaboo** [beetbox/beets#4369]
Spotify has a rate-limiting feature. If there are too many requests to the Spotify App it will prevent you from sending further requests. Fortunately, the response includes the `retry-after` value that we should be using to back off. 

I am just creating this issue so that we can keep a track of it based on @wisp3rwind comment [here](https://github.com/beetbox/beets/pull/4352#discussion_r895174817). 

Here are some reference links to implement this feature:
https://github.com/skuethe/MMM-Spotify/issues/172
https://github.com/felix-hilden/tekore/issues/163

**Comment by sampsyo** [comment]
Good idea! An ideal implementation of rate limiting would work by measuring the time since the _last_ call to the function—if the calls are naturally spaced out by some other work to be done, then there should be no need to `sleep` at all.

Something along the lines of the rate-limiting in the MusicBrainz library we use:
https://github.com/alastair/python-musicbrainzngs/blob/1638c6271e0beb9560243c2123d354461ec9f842/musicbrainzngs/musicbrainz.py#L376

…although I wrote that code a very long time ago, and maybe there are better Python stdlib facilities for this kind of pattern now?

**Comment by arsaboo** [comment]
If `sleep` is acceptable, we could do something like 
```
        if response.status_code == 429:
            seconds = r.headers['Retry-After']
            time.sleep(int(seconds))
            print(rate_limited, seconds)
```
If this approach works, I can create a PR.
