### ISSUE TITLE
spotify: spotify_updated is always a "null" date

### ISSUE THREAD

**Issue by arsaboo** [beetbox/beets#4491]
I just checked the `spotify_updated` values and all the values are `1969-12-31 19:00:00`, which prevents the use of any date-related queries. 
 
I have seen this elsewhere, but cannot figure out how to fix the issue. Here's how the date is currently being saved

https://github.com/beetbox/beets/blob/44a7cc74bfe673bcf960c5dc18716b38e33d5ad0/beetsplug/spotify.py#L651

Any idea how to fix it?

**Comment by sampsyo** [comment]
Aha—it looks like that code is assuming that a `DateField` can use a `datetime` object as its value. Unfortunately, that's not the case:
https://github.com/beetbox/beets/blob/44a7cc74bfe673bcf960c5dc18716b38e33d5ad0/beets/library.py#L120

You'll want to use `time.time()` instead of `datetime.datetime.now()`, as in this assignment to the `added` field:
https://github.com/beetbox/beets/blob/44a7cc74bfe673bcf960c5dc18716b38e33d5ad0/beets/dbcore/db.py#L599

**Comment by arsaboo** [comment]
Thanks....created a PR that fixes the bug.

**Comment by arsaboo** [comment]
@sampsyo Looks like it may be something else. In SQlite the date appears correctly:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/18319734/190880962-d11227bc-fbdf-4f7b-8459-1cf413e2710d.png">
For this track, the date still appears as 1969:
```
arsaboo@arsplex:~$ beet ls -f '$spotify_album_id - $path - $spotify_updated' album:"OK Jaanu"
3Ha8CM9px7D2fn25K4ijl6 - /data/music/Hindi Music/O/OK Jaanu (2017)/OK Jaanu (2017) - Sunn Bhavara.flac - 1969-12-31 19:00:00
```
The `added` date appears correctly.
