### ISSUE TITLE
Special character in track name causing logger to crash

### ISSUE THREAD

**Issue by thekakkun** [beetbox/beets#4903]
First of all, thanks for the awesome application!

I'm having an issue where the plugin logger crashes when trying to log data for a song called "0h }{eeiiy!"

### Problem
I'm currently writing a plugin to track playback status from MPD, and ran into this issue while trying to log information regarding `beets.library.Item` in an f-string:

```python
song: beets.library.Item
self._log.debug(f"{song})
```
Which should log the song info in the `artist - album - track` format, like so:

> Two Shell - lil spirits - 0h }{eeiiy!

Instead, the logger crashes with the message:

> ValueError: Single '}' encountered in format string

I assume this is caused by the odd track name (every other song I've tested has worked), but please let me know if more information is necessary.

### Setup

* OS: Fedora Linux 38
* Python version: 3.11.5
* beets version: 1.6.1
* plugin source code: https://github.com/thekakkun/music_utilities/blob/main/src/beetsplug/playback_tracker.py

**Comment by sampsyo** [comment]
Hello! Fortunately, it's an easy fix: the logging library fills in your `{}` parameters automatically (and lazily). So try this:

```py
self._log.debug("{}", song)
```

FWIW, the reason to do this, instead of using f-strings, is so that the logger doesn't even have to stringify `song` if this message will never be printed. (Otherwise, we'd be formatting a string argument and then throwing it away when debug messages are disabled.)
