### ISSUE TITLE
The Black Code Style - Extra empty lines (beets/ui/__init__.py) file

### ISSUE THREAD

**Issue by schaererPanda** [beetbox/beets#5367]
I reviewed the "black formatting" documentation in beets' style guide section in the Contributing file which states, "Black will enforce single empty lines between a class-level docstring and the first following field or method."  What I found on line 68 in the (beets/ui/__init__.py) file however, was two empty lines between a class-level ("UserError" - class, line 64) docstring and the following field.  This seems to violate the style convention.   

I believe the comment on line 69 should begin on line 68.

### Problem

I believe that this is a minor stylistic issue in the (beets/ui/__init__.py) file.  This minor issue does not effect functionality but might be important for consistency in the code.

### Setup

* OS: N/A
* Python version: N/A
* beets version: N/A
* Turning off plugins made problem go away (yes/no): N/A

My configuration (output of `beet config`) is:

N/A

**Comment by snejus** [comment]
Could you confirm you're talking about the following snippet?

```python
class UserError(Exception):
    """UI exception. Commands should throw this in order to display
    nonrecoverable errors to the user.
    """


# Encoding utilities.


def _in_encoding():
    """Get the encoding to use for *inputting* strings from the console."""
    return _stream_encoding(sys.stdin)
```

In this case the comment does not belong to the `UserError` class, therefore there are two empty lines inbetween.

Note that this code has been formatted by `black` - actually the entire code base is compliant with the style. All code that is being merged into the codebase must be formatted correctly otherwise the GitHub check will fail. 🙂
