### ISSUE TITLE
zsh: command not found: beet

### ISSUE THREAD

**Issue by btburton42** [beetbox/beets#601]
A quick and potentially easy question:
installed beets via:
`pip install beets`
says all my requirements are satisfied, but when type:
`beet`
into my terminal i get a command not found...

FYI : beets version is found via:
`pip freeze`
it outputs:
`beets==1.3.3`
i'm on a mac os x 10.7.5

**Comment by uhlhosting** [comment]
I got the same issue... I am not able to see why is not allowing it to work

`cosmicsound@Revenger:~|⇒  pip freeze
altgraph==0.10.2
ansible==2.4.3.0
asn1crypto==0.24.0
backports-abc==0.5
bcrypt==3.1.4
bdist-mpkg==0.5.0
beets==1.4.7
bonjour-py==0.3
cffi==1.11.5
cryptography==2.2.1
enum34==1.1.6
futures==3.2.0
idna==2.6
ipaddress==1.0.19
jellyfish==0.6.1
Jinja2==2.10
macholib==1.5.1
MarkupSafe==1.0
matplotlib==1.3.1
modulegraph==0.10.4
munkres==1.0.12
musicbrainzngs==0.6
mutagen==1.40.0
nose==1.3.7
numpy==1.8.0rc1
paramiko==2.4.1
py2app==0.7.3
pyasn1==0.4.2
pycparser==2.18
PyNaCl==1.2.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
PyYAML==3.12
scipy==0.13.0b1
singledispatch==3.4.0.3
six==1.11.0
tornado==5.0.2
Unidecode==1.0.22
vboxapi==1.0
xattr==0.6.4
cosmicsound@Revenger:~|⇒  pip show -f beets
Name: beets
Version: 1.4.7
Summary: music tagger and library organizer
Home-page: http://beets.io/
Author: Adrian Sampson
Author-email: adrian@radbox.org
License: MIT
Location: /Users/cosmicsound/Library/Python/2.7/lib/python/site-packages
Requires: six, mutagen, munkres, unidecode, musicbrainzngs, pyyaml, jellyfish, enum34
Required-by: 
Files:
  ../../../bin/beet
  beets-1.4.7-py2.7.egg-info
  beets-1.4.7-py2.7.egg-info/PKG-INFO
  beets-1.4.7-py2.7.egg-info/SOURCES.txt
  beets-1.4.7-py2.7.egg-info/dependency_links.txt
  beets-1.4.7-py2.7.egg-info/entry_points.txt
  beets-1.4.7-py2.7.egg-info/pbr.json
  beets-1.4.7-py2.7.egg-info/requires.txt
  beets-1.4.7-py2.7.egg-info/top_level.txt
  beets/__init__.py
  beets/__init__.pyc
  beets/__main__.py
  beets/__main__.pyc
  beets/art.py
  beets/art.pyc
  beets/autotag/__init__.py
  beets/autotag/__init__.pyc
  beets/autotag/hooks.py
  beets/autotag/hooks.pyc
  beets/autotag/match.py
  beets/autotag/match.pyc
  beets/autotag/mb.py
  beets/autotag/mb.pyc
  beets/config_default.yaml
  beets/dbcore/__init__.py
  beets/dbcore/__init__.pyc
  beets/dbcore/db.py
  beets/dbcore/db.pyc
  beets/dbcore/query.py
  beets/dbcore/query.pyc
  beets/dbcore/queryparse.py
  beets/dbcore/queryparse.pyc
  beets/dbcore/types.py
  beets/dbcore/types.pyc
  beets/importer.py
  beets/importer.pyc
  beets/library.py
  beets/library.pyc
  beets/logging.py
  beets/logging.pyc
  beets/mediafile.py
  beets/mediafile.pyc
  beets/plugins.py
  beets/plugins.pyc
  beets/ui/__init__.py
  beets/ui/__init__.pyc
  beets/ui/commands.py
  beets/ui/commands.pyc
  beets/ui/completion_base.sh
  beets/util/__init__.py
  beets/util/__init__.pyc
  beets/util/artresizer.py
  beets/util/artresizer.pyc
  beets/util/bluelet.py
  beets/util/bluelet.pyc
  beets/util/confit.py
  beets/util/confit.pyc
  beets/util/enumeration.py
  beets/util/enumeration.pyc
  beets/util/functemplate.py
  beets/util/functemplate.pyc
  beets/util/hidden.py
  beets/util/hidden.pyc
  beets/util/pipeline.py
  beets/util/pipeline.pyc
  beets/vfs.py
  beets/vfs.pyc
  beetsplug/__init__.py
  beetsplug/__init__.pyc
  beetsplug/absubmit.py
  beetsplug/absubmit.pyc
  beetsplug/acousticbrainz.py
  beetsplug/acousticbrainz.pyc
  beetsplug/badfiles.py
  beetsplug/badfiles.pyc
  beetsplug/beatport.py
  beetsplug/beatport.pyc
  beetsplug/bench.py
  beetsplug/bench.pyc
  beetsplug/bpd/__init__.py
  beetsplug/bpd/__init__.pyc
  beetsplug/bpd/gstplayer.py
  beetsplug/bpd/gstplayer.pyc
  beetsplug/bpm.py
  beetsplug/bpm.pyc
  beetsplug/bucket.py
  beetsplug/bucket.pyc
  beetsplug/chroma.py
  beetsplug/chroma.pyc
  beetsplug/convert.py
  beetsplug/convert.pyc
  beetsplug/cue.py
  beetsplug/cue.pyc
  beetsplug/discogs.py
  beetsplug/discogs.pyc
  beetsplug/duplicates.py
  beetsplug/duplicates.pyc
  beetsplug/edit.py
  beetsplug/edit.pyc
  beetsplug/embedart.py
  beetsplug/embedart.pyc
  beetsplug/embyupdate.py
  beetsplug/embyupdate.pyc
  beetsplug/export.py
  beetsplug/export.pyc
  beetsplug/fetchart.py
  beetsplug/fetchart.pyc
  beetsplug/filefilter.py
  beetsplug/filefilter.pyc
  beetsplug/freedesktop.py
  beetsplug/freedesktop.pyc
  beetsplug/fromfilename.py
  beetsplug/fromfilename.pyc
  beetsplug/ftintitle.py
  beetsplug/ftintitle.pyc
  beetsplug/fuzzy.py
  beetsplug/fuzzy.pyc
  beetsplug/gmusic.py
  beetsplug/gmusic.pyc
  beetsplug/hook.py
  beetsplug/hook.pyc
  beetsplug/ihate.py
  beetsplug/ihate.pyc
  beetsplug/importadded.py
  beetsplug/importadded.pyc
  beetsplug/importfeeds.py
  beetsplug/importfeeds.pyc
  beetsplug/info.py
  beetsplug/info.pyc
  beetsplug/inline.py
  beetsplug/inline.pyc
  beetsplug/ipfs.py
  beetsplug/ipfs.pyc
  beetsplug/keyfinder.py
  beetsplug/keyfinder.pyc
  beetsplug/kodiupdate.py
  beetsplug/kodiupdate.pyc
  beetsplug/lastgenre/__init__.py
  beetsplug/lastgenre/__init__.pyc
  beetsplug/lastgenre/genres-tree.yaml
  beetsplug/lastgenre/genres.txt
  beetsplug/lastimport.py
  beetsplug/lastimport.pyc
  beetsplug/lyrics.py
  beetsplug/lyrics.pyc
  beetsplug/mbcollection.py
  beetsplug/mbcollection.pyc
  beetsplug/mbsubmit.py
  beetsplug/mbsubmit.pyc
  beetsplug/mbsync.py
  beetsplug/mbsync.pyc
  beetsplug/metasync/__init__.py
  beetsplug/metasync/__init__.pyc
  beetsplug/metasync/amarok.py
  beetsplug/metasync/amarok.pyc
  beetsplug/metasync/itunes.py
  beetsplug/metasync/itunes.pyc
  beetsplug/missing.py
  beetsplug/missing.pyc
  beetsplug/mpdstats.py
  beetsplug/mpdstats.pyc
  beetsplug/mpdupdate.py
  beetsplug/mpdupdate.pyc
  beetsplug/permissions.py
  beetsplug/permissions.pyc
  beetsplug/play.py
  beetsplug/play.pyc
  beetsplug/plexupdate.py
  beetsplug/plexupdate.pyc
  beetsplug/random.py
  beetsplug/random.pyc
  beetsplug/replaygain.py
  beetsplug/replaygain.pyc
  beetsplug/rewrite.py
  beetsplug/rewrite.pyc
  beetsplug/scrub.py
  beetsplug/scrub.pyc
  beetsplug/smartplaylist.py
  beetsplug/smartplaylist.pyc
  beetsplug/sonosupdate.py
  beetsplug/sonosupdate.pyc
  beetsplug/spotify.py
  beetsplug/spotify.pyc
  beetsplug/the.py
  beetsplug/the.pyc
  beetsplug/thumbnails.py
  beetsplug/thumbnails.pyc
  beetsplug/types.py
  beetsplug/types.pyc
  beetsplug/web/__init__.py
  beetsplug/web/__init__.pyc
  beetsplug/web/static/backbone.js
  beetsplug/web/static/beets.css
  beetsplug/web/static/beets.js
  beetsplug/web/static/jquery.js
  beetsplug/web/static/underscore.js
  beetsplug/web/templates/index.html
  beetsplug/zero.py
  beetsplug/zero.pyc
cosmicsound@Revenger:~|⇒  echo $PATH
/usr/local/bin:/Users/cosmicsound/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/munki
cosmicsound@Revenger:~|⇒  pip uninstall munkres
Uninstalling munkres-1.0.12:
  Would remove:
    /Users/cosmicsound/Library/Python/2.7/lib/python/site-packages/munkres-1.0.12.dist-info/*
    /Users/cosmicsound/Library/Python/2.7/lib/python/site-packages/munkres.py
Proceed (y/n)? y
  Successfully uninstalled munkres-1.0.12
cosmicsound@Revenger:~|⇒  pip install munkres
Collecting munkres
  Using cached https://files.pythonhosted.org/packages/ea/f3/21d3c23017ba987e77286c5f7b6334366777919ced67f6bb9d48f5f5936c/munkres-1.0.12-py2.py3-none-any.whl
Installing collected packages: munkres
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/munkres.pyc'
Consider using the `--user` option or check the permissions.

cosmicsound@Revenger:~|⇒  pip install munkres --use
Collecting munkres
  Using cached https://files.pythonhosted.org/packages/ea/f3/21d3c23017ba987e77286c5f7b6334366777919ced67f6bb9d48f5f5936c/munkres-1.0.12-py2.py3-none-any.whl
Installing collected packages: munkres
Successfully installed munkres-1.0.12
cosmicsound@Revenger:~|⇒  pip install munkres --user
Requirement already satisfied: munkres in ./Library/Python/2.7/lib/python/site-packages (1.0.12)
cosmicsound@Revenger:~|⇒  bet                       
zsh: command not found: bet
cosmicsound@Revenger:~|⇒  beet
zsh: command not found: beet
`

**Comment by jackwilsdon** [comment]
@uhlhosting Looks like your `PATH` doesn't contain `/Users/cosmicsound/Library/Python/2.7/bin`, which is where `pip` is putting the `beet` command.
