### ISSUE TITLE
Option to clear all fields before applying a match

### ISSUE THREAD

**Issue by ecdlguy** [beetbox/beets#934]
An option/plugin to use only metadata from online sources. 
1. Don't import any of the files original tag data to the beets-database, only use this information to obtain matches from the online sources.
2. Completely clear/delete the entire existing tag before writing the new one.

**Comment by kooimens** [comment]
This would be nice!

**Comment by tummychow** [comment]
I am very interested in implementing this, as the current metadata on my music collection is hot garbage. The genre tag is particularly problematic because musicbrainz doesn't set it, so I end up importing whatever genre was already tagged on the track. I'd much prefer beets to be the originator for all the tags that end up on my imported music.

I'd like to confirm my understanding of the problem before I work on a PR:

- the changes should be made in the apply_metadata function [here](https://github.com/beetbox/beets/blob/master/beets/autotag/__init__.py#L61) or somewhere in the callchain leading there ([ImportTask.apply_metadata](https://github.com/beetbox/beets/blob/master/beets/importer.py#L534) is around where I'm thinking).
- to achieve the desired effect, every [field](https://github.com/beetbox/beets/blob/master/beets/library.py#L424) in the Item should be zeroed before applying the matched metadata. This zeroing should only happen if the user actually chooses apply.
- a new configuration option (`import.from_scratch`) should be added to toggle the behavior globally, with a corresponding flag (`--from-scratch`) to toggle the behavior at runtime. Anyone want to bikeshed on the name of this?
- I need to add tests for all new functionality.
